import type { IconName } from "@/components/icons";

// Os diferenciais da plataforma, visíveis na Hoje — cada card é âncora do
// tour guiado e leva para onde a feature vive.
export type StripItem = { anchor: string; icon: IconName; title: string; body: string; href: string; cta: string; isNew?: boolean };

export const STRIP_ITEMS: StripItem[] = [
  {
    anchor: "diff-scope",
    icon: "package",
    title: "Pacote e escopo sob controle",
    body: "Defina o pacote de cada cliente: cada post é contado, você é avisado quando passa e o extra vira valor aprovado.",
    href: "/clients",
    cta: "Definir num cliente",
    isNew: true,
  },
  {
    anchor: "diff-approval-link",
    icon: "link",
    title: "Aprovação por link",
    body: "O cliente aprova pelo WhatsApp, sem senha. O post aprovado já fica marcado na agenda, com histórico.",
    href: "/calendar",
    cta: "Enviar posts para aprovar",
    isNew: true,
  },
  {
    anchor: "diff-invoice",
    icon: "qr",
    title: "Fatura Pix sem taxa",
    body: "Fatura do fee com QR Pix da sua chave e lembrete pronto. O dinheiro cai direto na sua conta.",
    href: "/invoices",
    cta: "Abrir cobranças",
    isNew: true,
  },
  {
    anchor: "diff-carousel",
    icon: "layers",
    title: "Carrossel pronto",
    body: "Da ideia ao carrossel com as cores e o logo do cliente — é só baixar e postar, ou agendar.",
    href: "/clients",
    cta: "Criar num cliente",
    isNew: true,
  },
  {
    anchor: "diff-bio",
    icon: "link",
    title: "Link na bio e cliques",
    body: "Página de links por cliente e links curtos por post: você vê o que leva gente pro site, sem cookies.",
    href: "/links",
    cta: "Ver links",
    isNew: true,
  },
  {
    anchor: "diff-radar",
    icon: "radar",
    title: "Radar de IA",
    body: "Quando alguém pergunta pra uma IA, seu cliente aparece? Quem é citado e o que fazer para aparecer mais.",
    href: "/radar",
    cta: "Abrir radar",
    isNew: true,
  },
  {
    anchor: "diff-panel",
    icon: "users",
    title: "Teste com o público",
    body: "Compare versões do texto com as personas da estratégia antes de agendar. Simulação para descartar o fraco.",
    href: "/calendar",
    cta: "Testar um post",
    isNew: true,
  },
  {
    anchor: "diff-report",
    icon: "doc",
    title: "Relatório mensal em 1 clique",
    body: "Entregas, aprovações, posts, métricas e vendas do mês com resumo da IA — imprimível e compartilhável no portal.",
    href: "/clients",
    cta: "Escolher cliente",
  },
  {
    anchor: "diff-approval",
    icon: "check",
    title: "Aprovação que dispara ação",
    body: "Cliente aprovou no portal? Peça social vira rascunho no calendário e você recebe o aviso no WhatsApp.",
    href: "/settings",
    cta: "Ver regras",
  },
  {
    anchor: "diff-attendant",
    icon: "whatsapp",
    title: "Atendente de WhatsApp com IA",
    body: "Responde os clientes de cada marca 24/7 na voz dela, sem inventar preço, e chama uma pessoa quando precisa.",
    href: "/clients",
    cta: "Configurar por cliente",
  },
  {
    anchor: "diff-proposal",
    icon: "send",
    title: "Proposta pública em 5 minutos",
    body: "De um prospect a uma página com pitch, pacotes e prazo. Ele aceita sem login e já vira cliente.",
    href: "/prospecting",
    cta: "Abrir prospecção",
  },
  {
    anchor: "diff-calendar",
    icon: "calendar",
    title: "Calendário de conteúdo",
    body: "Semana ou mês por cliente, status com um clique e aviso dos dias sem conteúdo.",
    href: "/calendar",
    cta: "Abrir calendário",
  },
  {
    anchor: "diff-public-page",
    icon: "globe",
    title: "Página pública da agência",
    body: "Portfólio, clientes e depoimentos em /a/sua-agencia, com formulário que vira prospect e avisa você na hora.",
    href: "/settings#pagina-publica",
    cta: "Configurar página",
  },
  {
    anchor: "diff-pulse",
    icon: "target",
    title: "Pulso do cliente e NPS",
    body: "Depois de cada aprovação e uma vez por mês o cliente responde em 1 clique; a cada trimestre, o NPS. Quem está esfriando aparece aqui.",
    href: "/insights#pulso",
    cta: "Ver quem está em risco",
  },
  {
    anchor: "diff-margin",
    icon: "clock",
    title: "Horas e margem por cliente",
    body: "Cronômetro por demanda, custo/hora da equipe e fee mensal: quanto cada cliente rende de verdade — e quem dá prejuízo.",
    href: "/finance",
    cta: "Ver margem do mês",
  },
  {
    anchor: "diff-brand-voice",
    icon: "layers",
    title: "Guardião da voz da marca",
    body: "Antes de agendar um post ou enviar uma resposta, um clique checa tom, termos proibidos, CTA, hashtags e alegações sem fonte — e reescreve no tom.",
    href: "/calendar",
    cta: "Checar um post",
  },
  {
    anchor: "diff-campaign",
    icon: "megaphone",
    title: "Campanha de 30 dias",
    body: "Briefing + objetivo + canais viram um mês inteiro de posts escritos (gancho, legenda, CTA, brief da imagem), já no calendário como rascunho.",
    href: "/clients",
    cta: "Gerar em um cliente",
  },
  {
    anchor: "diff-learnings",
    icon: "chart",
    title: "O que funciona pra este cliente",
    body: "Posts cruzados com as vendas e métricas dos dias seguintes: melhor formato, dia e horário, o que menos rende — e uma leitura de 3 linhas da IA.",
    href: "/clients",
    cta: "Ver num cliente",
  },
];
