// Dicionário PT→EN da interface da plataforma (chrome). Conteúdo gerado por
// IA nunca é traduzido: a tradução é por correspondência exata com as strings
// da UI — textos de entregáveis não batem com o dicionário e passam intocados
// (eles já são localizados por cliente na geração).
export const UI_DICT: Record<string, string> = {
  "Elo da agência": "Agency rank",
  "Progresso para o próximo elo": "Progress to the next rank",
  "Clientes ativos": "Active clients",
  "Demandas pagas": "Paid demands",
  "Entregáveis gerados": "Deliverables generated",
  "Nota média das entregas": "Average delivery score",
  "Profissionais na rede": "Professionals in network",
  "Ações nos últimos 7 dias": "Actions in the last 7 days",
  "Demandas concluídas": "Completed demands",

  // Navegação / layout
  "Clientes": "Clients",
  "Prospecção": "Prospecting",
  "Profissionais": "Professionals",
  "Agenda": "Schedule",
  "Ideias": "Ideas",
  "Treinamento": "Training",
  "Configurações": "Settings",
  "Portal": "Portal",
  "Novo cliente": "New client",
  // Comuns
  "Salvar": "Save",
  "Cancelar": "Cancel",
  "Excluir": "Delete",
  "Editar": "Edit",
  "Enviar": "Send",
  "Abrir": "Open",
  "Carregando...": "Loading...",
  "Salvando...": "Saving...",
  "Enviando...": "Sending...",
  "Gerando...": "Generating...",
  "Criando...": "Creating...",
  "Copiar": "Copy",
  "Copiado ✓": "Copied ✓",
  "Copiar legenda": "Copy caption",
  "Copiar link": "Copy link",
  "Copiar SVG": "Copy SVG",
  "Copiar resumo": "Copy summary",
  "Baixar": "Download",
  "Baixar ⬇": "Download ⬇",
  "⬇ Baixar": "⬇ Download",
  "Salvar alterações": "Save changes",
  "cancelar": "cancel",
  "Confirmar": "Confirm",
  "opcional": "optional",
  "Aplicado ✓": "Applied ✓",
  // Dashboard home
  "Carregando clientes...": "Loading clients...",
  "+ Novo cliente": "+ New client",
  "Cadastrar primeiro cliente": "Add your first client",
  "Desde": "Since",
  // Workspace tabs
  "Dashboard": "Dashboard",
  "Briefing": "Briefing",
  "Estratégia": "Strategy",
  "Radar": "Radar",
  "Campanha": "Campaign",
  "ROI & Roadmap": "ROI & Roadmap",
  "Social": "Social",
  "Posts": "Posts",
  "Identidade": "Identity",
  "Ofertas": "Offers",
  "Landing pages": "Landing pages",
  "Demandas": "Jobs",
  "Relatório": "Report",
  "✦ Gerar kit completo": "✦ Generate full kit",
  "Gerando kit...": "Generating kit...",
  // Client form
  "Nome do cliente *": "Client name *",
  "País / mercado-alvo": "Country / target market",
  "Idioma dos entregáveis": "Deliverables language",
  "Português (BR)": "Portuguese (BR)",
  "English (US)": "English (US)",
  "Segmento": "Industry",
  "Site": "Website",
  "Sobre a empresa": "About the company",
  "Público-alvo": "Target audience",
  "Objetivos de marketing": "Marketing goals",
  "Tom de voz": "Tone of voice",
  "Verba mensal": "Monthly budget",
  "Cores / identidade atual": "Current colors / identity",
  "Canais ativos": "Active channels",
  "Diferenciais": "Differentiators",
  "Concorrentes": "Competitors",
  "Recursos & capacidade produtiva": "Resources & production capacity",
  "Observações extras": "Extra notes",
  "Criar cliente": "Create client",
  "Arquivos da marca": "Brand files",
  "⬆ Enviar arquivo": "⬆ Upload file",
  "Identidade visual": "Visual identity",
  "Projeto (PSD/AI)": "Project file (PSD/AI)",
  "Outro": "Other",
  "Excluir cliente": "Delete client",
  // Generator tab
  "Instruções adicionais / feedback da equipe (opcional)":
    "Additional instructions / team feedback (optional)",
  "Refinar a partir da versão selecionada": "Refine from the selected version",
  "Carregando histórico...": "Loading history...",
  "Excluir versão": "Delete version",
  "📄 PDF": "📄 PDF",
  "A IA está trabalhando — isso pode levar 1-3 minutos...":
    "The AI is working — this can take 1-3 minutes...",
  // Botões de geração
  "Gerar análise estratégica": "Generate strategic analysis",
  "Rodar radar agora": "Run radar now",
  "Gerar plano de campanha": "Generate campaign plan",
  "Gerar ROI & roadmap": "Generate ROI & roadmap",
  "Gerar calendário": "Generate calendar",
  "Gerar posts": "Generate posts",
  "Gerar identidade": "Generate identity",
  "Gerar oportunidades": "Generate opportunities",
  "Gerar landing page": "Generate landing page",
  "Gerar relatório": "Generate report",
  "Mês da campanha": "Campaign month",
  "Foco especial (opcional)": "Special focus (optional)",
  "Mês": "Month",
  "Posts por semana": "Posts per week",
  "Tema do post": "Post topic",
  "Canal": "Channel",
  "Formato": "Format",
  "Variações": "Variations",
  "Direcionamento (opcional)": "Direction (optional)",
  "Horizonte": "Timeframe",
  "Métricas atuais (opcional)": "Current metrics (optional)",
  "Período": "Period",
  "Público do relatório": "Report audience",
  "Objetivo": "Goal",
  "Oferta / produto em destaque": "Featured offer / product",
  "CTA principal": "Main CTA",
  "Direção visual (opcional)": "Visual direction (optional)",
  // Renderers (títulos de seção)
  "Sumário executivo": "Executive summary",
  "Tendências de mercado (pesquisa real)": "Market trends (real research)",
  "Target buyers — deep dive": "Target buyers — deep dive",
  "Dores": "Pains",
  "Desejos": "Desires",
  "Best fits — onde apostar agora": "Best fits — where to bet now",
  "Metas": "Goals",
  "Momento do mercado": "Market moment",
  "Destaques recentes": "Recent highlights",
  "Mudanças de tendência": "Trend shifts",
  "Ajustes recomendados": "Recommended adjustments",
  "Objetivos & KPIs": "Objectives & KPIs",
  "Semana a semana": "Week by week",
  "Canais": "Channels",
  "Verba": "Budget",
  "Riscos & pontos de atenção": "Risks & watch-outs",
  "Influenciadores recomendados (perfis reais)": "Recommended influencers (real profiles)",
  "Resumo": "Summary",
  "Investimento total": "Total investment",
  "Retorno projetado": "Projected return",
  "Payback": "Payback",
  "Métricas — antes → projetado → real": "Metrics — before → projected → actual",
  "Métrica": "Metric",
  "Antes": "Before",
  "Projetado": "Projected",
  "Real": "Actual",
  "Salvar valores reais": "Save actual values",
  "Roadmap": "Roadmap",
  "Investimento mensal": "Monthly investment",
  "Premissas": "Assumptions",
  "Estratégia do mês": "Month's strategy",
  "Essência da marca": "Brand essence",
  "Conceitos de logo": "Logo concepts",
  "Paleta": "Palette",
  "Tipografia": "Typography",
  "Aplicações prioritárias": "Priority applications",
  "Faça": "Do",
  "Não faça": "Don't",
  "Leitura do momento": "Current read",
  "O que produzir/ofertar com o que você tem": "What to produce/offer with what you have",
  "Reposicionamento do que você já faz": "Repositioning what you already do",
  "Frentes de trabalho": "Workstreams",
  "Qualidade das entregas": "Delivery quality",
  "Próximos passos": "Next steps",
  "Riscos & pendências": "Risks & pending items",
  "🎨 Direção de arte:": "🎨 Art direction:",
  "CTA:": "CTA:",
  "✏️ Editar": "✏️ Edit",
  "→ Criar demanda de produção": "→ Create production job",
  "✓ Demanda criada (aba Demandas)": "✓ Job created (Jobs tab)",
  "🕐 Agendar publicação": "🕐 Schedule post",
  "🕐 Agendado ✓ (veja em Agenda)": "🕐 Scheduled ✓ (see Schedule)",
  "🎯 Gerar campanha desta aposta": "🎯 Build campaign from this bet",
  "📋 Criar demanda desta aposta": "📋 Create job from this bet",
  "✍️ Gerar posts para esta persona": "✍️ Generate posts for this persona",
  "🎯 Aplicar em campanha": "🎯 Apply to campaign",
  "✍️ Gerar posts sobre isso": "✍️ Generate posts about this",
  "📋 Criar demanda": "📋 Create job",
  "📋 Criar demanda desta semana": "📋 Create job for this week",
  "📆 Gerar calendário social deste plano": "📆 Generate social calendar from this plan",
  "✍️ Gerar posts do tema": "✍️ Generate posts from the theme",
  "🎯 Campanha desta fase": "🎯 Campaign for this phase",
  "📋 Criar demanda desta fase": "📋 Create job for this phase",
  "🎯 Campanha de lançamento": "🎯 Launch campaign",
  "✍️ Posts sobre isso": "✍️ Posts about this",
  "🎯 Virar campanha": "🎯 Turn into campaign",
  "🎯 Enfatizar em campanha": "🎯 Emphasize in campaign",
  "IA escrevendo o brief...": "AI writing the brief...",
  // Projects tab
  "+ Nova demanda": "+ New job",
  "✦ Gerar demandas do plano (IA)": "✦ Generate jobs from the plan (AI)",
  "✦ Escrever brief com IA": "✦ Write brief with AI",
  "Analisando o plano...": "Analyzing the plan...",
  "Criar demanda": "Create job",
  "✓ Criada": "✓ Created",
  "Execução": "Execution",
  "🌐 Com freelas da plataforma": "🌐 With platform freelancers",
  "🏠 Interna (meu time)": "🏠 Internal (my team)",
  "Título *": "Title *",
  "Local da produção": "Production location",
  "Brief": "Brief",
  "Skills necessárias": "Required skills",
  "Prazo": "Deadline",
  "← Todas as demandas": "← All jobs",
  "Editar demanda": "Edit job",
  "Fechar edição": "Close editing",
  "Salvar demanda": "Save job",
  "Título": "Title",
  "Profissional": "Professional",
  "Execução interna": "Internal execution",
  "Vinculado:": "Assigned:",
  "Desvincular": "Unassign",
  "✦ Match por IA": "✦ AI Match",
  "Analisando fit...": "Analyzing fit...",
  "Ver portfolio →": "View portfolio →",
  "Vincular ao projeto": "Assign to project",
  "Aceitar": "Accept",
  "Recusar": "Reject",
  "⭐ Definir como preferido": "⭐ Set as preferred",
  "Referências (fotos base)": "References (base assets)",
  "⬆ Enviar referência": "⬆ Upload reference",
  "Modelo": "Model",
  "Produto/Peça": "Product/Piece",
  "Equipe/Pessoas": "Team/People",
  "Local/Cenário": "Location/Scene",
  "Referência de estilo": "Style reference",
  "Sketch de referência (IA)": "Reference sketch (AI)",
  "✏️ Gerar sketch da composição": "✏️ Generate composition sketch",
  "↻ Regerar sketch": "↻ Regenerate sketch",
  "Desenhando...": "Drawing...",
  "Direção de arte:": "Art direction:",
  "⬇ Baixar SVG para enviar ao profissional": "⬇ Download SVG to send to the professional",
  "Para um sketch mais fiel, envie nas Referências:": "For a more faithful sketch, upload to References:",
  "Reuniões": "Meetings",
  "Agendar": "Schedule",
  "entrar ↗": "join ↗",
  "📅 Calendar": "📅 Calendar",
  "Chat do projeto": "Project chat",
  "Nenhuma mensagem ainda.": "No messages yet.",
  "Agência": "Agency",
  "Cliente": "Client",
  "Escreva uma mensagem...": "Write a message...",
  "Entregas": "Deliveries",
  "⬆ Enviar imagem": "⬆ Upload image",
  "Título da entrega (opcional)": "Delivery title (optional)",
  "💰 Reservar pagamento (escrow) e iniciar produção": "💰 Reserve payment (escrow) and start production",
  "✅ Aprovar entrega": "✅ Approve delivery",
  "↩ Voltar para produção (ajustes)": "↩ Back to production (revisions)",
  "🏦 Liberar pagamento ao profissional": "🏦 Release payment to the professional",
  "🚀 Iniciar produção": "🚀 Start production",
  "↩ Voltar para produção": "↩ Back to production",
  "✔ Concluir demanda": "✔ Complete job",
  // Status de demanda / escrow / candidatura
  "Aberta": "Open",
  "Profissional vinculado": "Professional assigned",
  "Em produção": "In production",
  "Em revisão": "In review",
  "Aprovada": "Approved",
  "Paga & concluída": "Paid & completed",
  "Pagamento não reservado": "Payment not reserved",
  "Pagamento reservado (garantido)": "Payment reserved (guaranteed)",
  "Pagamento liberado ao profissional": "Payment released to the professional",
  "Aguardando análise": "Awaiting review",
  "Aceita": "Accepted",
  "Recusada": "Rejected",
  // Deliverable viewer
  "Analisando...": "Analyzing...",
  "🔍 Analisar com IA": "🔍 Analyze with AI",
  "Reanalisar com IA": "Re-analyze with AI",
  "Análise da IA — no contexto da campanha": "AI analysis — in campaign context",
  "Pontos fortes": "Strengths",
  "Melhorias": "Improvements",
  "Notas de revisão para o profissional": "Revision notes for the professional",
  "Resolver ✓": "Resolve ✓",
  "Reabrir": "Reopen",
  "Descreva o ajuste neste ponto...": "Describe the fix at this spot...",
  "todos": "everyone",
  // Professionals
  "+ Cadastrar profissional": "+ Register professional",
  "Cadastro de profissional": "Professional registration",
  "Fotógrafo(a)": "Photographer",
  "Designer": "Designer",
  "Nome *": "Name *",
  "Atuação": "Role",
  "Localização (cidade/UF) *": "Location (city/state) *",
  "E-mail": "Email",
  "WhatsApp/telefone": "WhatsApp/phone",
  "Faixa de preço": "Price range",
  "Skills": "Skills",
  "Especialidades": "Specialties",
  "Foco de mercado": "Market focus",
  "Bio": "Bio",
  "Portfolio (links)": "Portfolio (links)",
  "+ Adicionar link": "+ Add link",
  "Criar perfil": "Create profile",
  "Editar perfil": "Edit profile",
  "Excluir perfil": "Delete profile",
  "Perfil": "Profile",
  "Demandas ativas": "Active jobs",
  "Minhas demandas": "My jobs",
  "Oportunidades abertas na plataforma": "Open opportunities on the platform",
  "✋ Candidatar-se": "✋ Apply",
  "Mensagem de apresentação": "Introduction message",
  "Enviar candidatura": "Send application",
  "💡 Ideias para mim": "💡 Ideas for me",
  "Carregando perfil...": "Loading profile...",
  // Tiers
  "Bronze": "Bronze",
  "Prata": "Silver",
  "Ouro": "Gold",
  "Platina": "Platinum",
  // Prospecting
  "Prospecção de clientes": "Client prospecting",
  "Nicho *": "Niche *",
  "Região *": "Region *",
  "Critérios extras (opcional)": "Extra criteria (optional)",
  "🔎 Descobrir potenciais clientes": "🔎 Discover potential clients",
  "Pesquisando...": "Searching...",
  "Novo": "New",
  "Contatado": "Contacted",
  "Convertido em cliente": "Converted to client",
  "Descartado": "Discarded",
  "Marcar contatado": "Mark contacted",
  "Converter em cliente ✦": "Convert to client ✦",
  "Descartar": "Discard",
  "Abrir cliente →": "Open client →",
  "site ↗": "website ↗",
  // Ideas
  "Motor de ideias": "Ideas engine",
  "Para quem": "For whom",
  "Para a agência": "For the agency",
  "Para um cliente": "For a client",
  "Para um profissional": "For a professional",
  "Selecione...": "Select...",
  "💡 Gerar ideias com base nas trends de hoje": "💡 Generate ideas from today's trends",
  "🎯 Gerar campanha com esta ideia": "🎯 Build campaign from this idea",
  "📋 Criar demanda desta ideia (IA escreve o brief)": "📋 Create job from this idea (AI writes the brief)",
  "🔬 Estudo de mercado da conta": "🔬 Account market study",
  "Próximo passo:": "Next step:",
  // Agenda
  "✦ Recomendar reuniões (IA)": "✦ Recommend meetings (AI)",
  "Analisando as contas...": "Analyzing accounts...",
  "Reuniões recomendadas": "Recommended meetings",
  "Participantes:": "Participants:",
  "Por quê:": "Why:",
  "✓ Agendada": "✓ Scheduled",
  "Fila de publicações": "Publishing queue",
  "✓ Marcar publicado": "✓ Mark published",
  "✓ Publicado": "✓ Published",
  "⏰ Na hora — publicar agora": "⏰ Due — publish now",
  "Agendar manualmente": "Schedule manually",
  "Reunião geral...": "General meeting...",
  "Link (Meet/Zoom)": "Link (Meet/Zoom)",
  "Link Meet/Zoom (opcional)": "Meet/Zoom link (optional)",
  "Próximas reuniões": "Upcoming meetings",
  "Realizadas": "Past",
  "Nada agendado.": "Nothing scheduled.",
  // Settings
  "Whitelabel — a plataforma com a sua marca": "Whitelabel — the platform with your brand",
  "Nome da agência": "Agency name",
  "Tagline (rodapé)": "Tagline (footer)",
  "Cor de destaque": "Accent color",
  "Custo & features de IA": "AI cost & features",
  "💸 Econômico": "💸 Economy",
  "⚖️ Equilibrado": "⚖️ Balanced",
  "👑 Premium": "👑 Premium",
  "Gerador de landing pages": "Landing page generator",
  "Chaves de API": "API keys",
  "Salvar configurações": "Save settings",
  "Convites para externos": "Invites for externals",
  "Integrações": "Integrations",
  "Em breve": "Coming soon",
  // Portais
  "Entrar na plataforma": "Enter the platform",
  "🏢 Agência": "🏢 Agency",
  "👤 Cliente": "👤 Client",
  "📸 Profissional": "📸 Professional",
  "Entrar como agência": "Enter as agency",
  "Entrar como cliente": "Enter as client",
  "Entrar como profissional": "Enter as professional",
  "Selecione sua empresa...": "Select your company...",
  "Selecione seu perfil...": "Select your profile...",
  "Ainda não sou cadastrado →": "Not registered yet →",
  "Quero me cadastrar →": "I want to register →",
  "Portal do cliente": "Client portal",
  "Produções em andamento": "Productions in progress",
  "Suas landing pages": "Your landing pages",
  "📄 Salvar em PDF": "📄 Save as PDF",
  "Cadastre sua empresa": "Register your company",
  "Cadastro recebido! 🎉": "Registration received! 🎉",
  // Dashboard do cliente
  "Elo da conta": "Account tier",
  "Aguardando revisão": "Awaiting review",
  "Ações rápidas": "Quick actions",
  "📡 Rodar radar de mercado": "📡 Run market radar",
  "📄 Gerar relatório": "📄 Generate report",
  "💡 Ideias para esta conta": "💡 Ideas for this account",
  "👤 Ver como cliente": "👤 View as client",
  "Último pulso do mercado": "Latest market pulse",
  "Entregáveis": "Deliverables",
  "Demandas recentes": "Recent jobs",
  "gerar →": "generate →",
  "Agenda completa →": "Full schedule →",
  "Carregando dashboard...": "Loading dashboard...",
  // Labels de tipos
  "Estratégia & Deep Dive": "Strategy & Deep Dive",
  "Radar de mercado": "Market radar",
  "Plano de campanha": "Campaign plan",
  "Calendário social": "Social calendar",
  "Landing page": "Landing page",
  "Relatório executivo": "Executive report",
  "Oportunidades de oferta": "Offer opportunities",
};

// Regras para strings com interpolação (aplicadas com cautela — só padrões
// inequívocos da UI)
export const UI_REGEX_RULES: [RegExp, string][] = [
  [/^Desde (.+)$/, "Since $1"],
  [/^até (.+)$/, "by $1"],
  [/^esforço (.+)$/, "effort $1"],
  [/(\d+) demandas concluídas/, "$1 completed jobs"],
  [/^Candidatura: (.+)$/, "Application: $1"],
];
