// Dicionário PT→EN da rodada 3 (mesma regra do ui-dict: correspondência exata
// com o texto da interface). Separado só para não inchar o arquivo principal.
export const UI_DICT_R3: Record<string, string> = {
  // Navegação consolidada
  "Crescimento": "Growth",
  "Mais": "More",
  "Conteúdo": "Content",
  "Visão geral": "Overview",
  "Plano": "Plan",
  "Operação": "Operations",
  "Radar do mercado": "Market radar",
  "Insights": "Insights",
  "Propostas": "Proposals",
  "Página pública": "Public page",
  "Navegação": "Navigation",
  "Seções do cliente": "Client sections",
  "Abas da seção": "Section tabs",
  "Aba do workspace": "Workspace tab",
  "Onde a agência encontra cliente novo e vende mais para quem já está com você.":
    "Where your agency finds new clients and sells more to the ones you already have.",
  "A IA procura empresas do seu nicho e região, com motivo e primeira mensagem para cada uma.":
    "The AI finds businesses in your niche and region, each with a reason and a first message.",
  "Buscar prospects": "Find prospects",
  "Nenhum prospect ainda": "No prospects yet",
  "Uma página com pitch, pacotes e prazo. O prospect aceita sem login e já vira cliente.":
    "A page with the pitch, packages and deadline. The prospect accepts without logging in and becomes a client.",
  "Criar proposta": "Create a proposal",
  "Serviços, trabalhos e depoimentos no seu endereço. O formulário vira prospect e avisa você.":
    "Services, work and testimonials at your own address. The form turns into a prospect and alerts you.",
  "Configurar página": "Set up the page",
  "Ainda não publicada": "Not published yet",
  // Admin: custos, teto e LGPD
  "Custos de IA": "AI costs",
  "Margem por conta (30 dias)": "Margin per account (30 days)",
  "Custo por ação e modelo (30 dias)": "Cost per action and model (30 days)",
  "Sem receita nem uso de IA nos últimos 30 dias.": "No revenue or AI usage in the last 30 days.",
  "Nenhum uso de IA registrado.": "No AI usage recorded.",
  "Receita": "Revenue",
  "Custo IA": "AI cost",
  "Margem": "Margin",
  "Chamadas": "Calls",
  "Buscas": "Searches",
  "Ação": "Action",
  "Modelo": "Model",
  "Salvar teto": "Save cap",
  "Teto de IA salvo.": "AI cap saved.",
  "vazio = padrão do plano": "empty = plan default",
  "Dados pessoais (LGPD)": "Personal data (LGPD)",
  "Exportar dados da conta": "Export account data",
  "Excluir conta": "Delete account",
  "Para excluir, digite": "To delete, type",
  "Conta excluída. Lançamentos financeiros ficam sem vínculo pessoal.": "Account deleted. Financial records stay without any personal link.",
  "A exclusão apaga a conta e o que é só dela; pagamentos e custos ficam para a contabilidade, sem vínculo com a pessoa.":
    "Deleting removes the account and what belongs only to it; payments and costs stay for accounting, with no link to the person.",
  "Escreva o motivo da concessão.": "Write the reason for the grant.",
  "Digite o nome de usuário exato para confirmar.": "Type the exact username to confirm.",
  "Use Minha conta para excluir a própria conta.": "Use My account to delete your own account.",
  "Esta conta não usa IA.": "This account doesn't use AI.",
  // Aprovação por link
  "Enviar para aprovação": "Send for approval",
  "Aprovação por link": "Approval by link",
  "Mande posts e entregas pelo WhatsApp. O cliente aprova sem senha e o post já entra na agenda.":
    "Send posts and deliveries over WhatsApp. The client approves without a password and the post goes straight into the schedule.",
  "O cliente aprova pelo celular, sem login. O post aprovado já entra na agenda.":
    "The client approves from their phone, no login. An approved post goes straight into the schedule.",
  "Link pronto. O cliente abre no celular e aprova sem senha.": "Link ready. The client opens it on their phone and approves without a password.",
  "Enviar no WhatsApp": "Send on WhatsApp",
  "Copiar link": "Copy link",
  "Copiar mensagem": "Copy message",
  "Em reunião? O cliente aponta a câmera e abre direto.": "In a meeting? The client points their camera and it opens.",
  "O que vai para aprovação": "What goes for approval",
  "Nada pendente: crie posts no calendário ou suba entregas nas demandas deste cliente.":
    "Nothing pending: create posts in the calendar or upload deliveries in this client's jobs.",
  "Entrega": "Delivery",
  "Validade": "Valid for",
  "WhatsApp do cliente (opcional)": "Client's WhatsApp (optional)",
  "Gerando...": "Generating...",
  "Links enviados": "Links sent",
  "Aberto": "Open",
  "Expirado": "Expired",
  "Encerrado": "Closed",
  "Reenviar": "Resend",
  "Encerrar": "Close",
  "Encerrar este link? O cliente passa a ver que ele expirou.": "Close this link? The client will see that it has expired.",
  "Cadastre um cliente primeiro.": "Add a client first.",
  "Aguardando o cliente": "Waiting for the client",
  "Aprovado pelo cliente": "Approved by the client",
  "Cliente pediu ajuste": "Client asked for changes",
  "Ajuste pedido pelo cliente": "Changes asked by the client",
  "Pelo link de aprovação": "Through the approval link",
  "⏳ Aguardando aprovação há mais de 48h": "⏳ Waiting for approval for over 48h",
  "3 dias": "3 days",
  "7 dias": "7 days",
  "14 dias": "14 days",
  "30 dias": "30 days",
  "Escolha pelo menos um item.": "Pick at least one item.",
  "Escolha pelo menos um post ou entrega.": "Pick at least one post or delivery.",
  "Algum item não é deste cliente ou já foi publicado.": "Some item isn't from this client or was already published.",
  // Pacote do cliente + escopo
  "Pacote": "Package",
  "Pacote do cliente": "Client package",
  "Ver pacote": "View package",
  "Definir pacote": "Set up package",
  "Diga o que o fee cobre por mês. Pedido fora do combinado vira extra com valor aprovado pelo cliente.":
    "Say what the monthly fee covers. Anything outside it becomes an extra with a price the client approves.",
  "O que o fee cobre por mês": "What the fee covers each month",
  "O cliente vê quanto já usou. Pedido que passa do pacote só vira demanda depois que ele aprova o valor do extra — e o extra entra na fatura do mês.":
    "The client sees how much is used. A request beyond the package only becomes a job after they approve the extra's price — and the extra goes on that month's invoice.",
  "Comece por um modelo e ajuste:": "Start from a template and adjust:",
  "Social básico": "Social basics",
  "Social + tráfego": "Social + ads",
  "Conteúdo premium": "Premium content",
  "Item": "Item",
  "Unidade": "Unit",
  "Por mês": "Per month",
  "Extra (R$/un.)": "Extra (R$/unit)",
  "Remover item": "Remove item",
  "+ Adicionar item": "+ Add item",
  "Novo item": "New item",
  "Acumular o que sobrar para o mês seguinte (um mês)": "Carry what's left over to the next month (one month)",
  "Salvar pacote": "Save package",
  "Sem pacote": "No package",
  "Tirar o pacote deste cliente? Os pedidos voltam a virar demanda direto.": "Remove this client's package? Requests will become jobs directly again.",
  "Defina o pacote para acompanhar o uso.": "Set up the package to track usage.",
  "Pedidos do cliente": "Client requests",
  "Os pedidos feitos no portal aparecem aqui, com o que cabe no pacote e o que é extra.":
    "Requests made in the portal show up here, with what fits the package and what's extra.",
  "Aguardando o cliente aprovar o valor": "Waiting for the client to approve the price",
  "Extra aprovado": "Extra approved",
  "Dentro do pacote": "Within the package",
  "Incluído sem custo": "Included at no cost",
  "Incluir sem custo": "Include at no cost",
  "Cancelar pedido": "Cancel request",
  "posts": "posts",
  "reels": "reels",
  "carrosséis": "carousels",
  "stories": "stories",
  "demandas": "jobs",
  "reuniões": "meetings",
  "relatórios": "reports",
  "Posts no feed": "Feed posts",
  "Peças para anúncio": "Ad creatives",
  "Relatório mensal": "Monthly report",
  "Produções extras (foto, vídeo, arte)": "Extra productions (photo, video, design)",
  "Solicitar uma produção": "Request a production",
  "Pedido enviado! Cabe no seu pacote e a agência já recebeu.": "Request sent! It fits your package and the agency already has it.",
  "Esse pedido passa do seu pacote. Aprove o valor abaixo para a agência começar.": "This request goes beyond your package. Approve the price below so the agency can start.",
  "Continuar": "Continue",
  "Enviar solicitação": "Send request",
  "Enviando...": "Sending...",
  "O que é": "What it is",
  "Quantidade": "Quantity",
  "Enviar e ver o valor": "Send and see the price",
  "Enviar pedido": "Send request",
  "Voltar": "Back",
  "Extras do mês": "This month's extras",
  "Os extras aprovados entram na fatura do mês de cada cliente.": "Approved extras go on each client's invoice for the month.",
  "Quem aprova o valor do extra é o cliente.": "Only the client approves the extra's price.",
  "Este pedido já foi decidido.": "This request has already been decided.",
  "Conte o que você precisa.": "Tell us what you need.",
  "Escolha um item do pacote.": "Pick an item from the package.",
  "Confira os itens do pacote.": "Check the package items.",
  "Classificação de exemplo (modo de teste).": "Example classification (test mode).",
  // Cobranças (Pix)
  "Cobranças": "Billing",
  "Fatura do fee com Pix copia e cola e QR. O dinheiro vai direto para a sua conta, sem taxa da Marqa.":
    "Fee invoices with a Pix copy-and-paste code and QR. The money goes straight to your account, with no Marqa fee.",
  "Cadastre sua chave Pix em": "Add your Pix key in",
  "Configurações → Recebimentos": "Settings → Payments",
  "para enviar faturas.": "to send invoices.",
  "A receber": "To receive",
  "Atrasadas": "Overdue",
  "Cliente avisou que pagou": "Client says they paid",
  "Nova fatura": "New invoice",
  "No dia 1 a Marqa cria o rascunho de cada cliente com fee (mais os extras aprovados). Você confere e envia. O Pix cai direto na sua conta; a confirmação é sua.":
    "On day 1 Marqa drafts an invoice for each client with a fee (plus approved extras). You check it and send it. The Pix lands in your account; you confirm it.",
  "Escolha o cliente": "Choose the client",
  "Mês": "Month",
  "Criar rascunho": "Create draft",
  "Baixar CSV": "Download CSV",
  "Nenhuma fatura ainda. Defina o fee mensal do cliente em Horas & margem e crie o primeiro rascunho.":
    "No invoices yet. Set the client's monthly fee in Hours & margin and create the first draft.",
  "Rascunho": "Draft",
  "Enviada": "Sent",
  "Cliente diz que pagou": "Client says they paid",
  "Paga": "Paid",
  "Cancelada": "Canceled",
  "Atrasada": "Overdue",
  "Enviar": "Send",
  "Editar": "Edit",
  "Confirmar pagamento": "Confirm payment",
  "Lembrar no WhatsApp": "Remind on WhatsApp",
  "Desfazer confirmação": "Undo confirmation",
  "Ver página do cliente ↗": "View client page ↗",
  "Cancelar fatura": "Cancel invoice",
  "Cancelar esta fatura? Os extras voltam para a próxima.": "Cancel this invoice? The extras move to the next one.",
  "O pagamento cai direto na sua conta; a confirmação é manual. A Marqa não cobra taxa sobre as faturas.":
    "The payment lands straight in your account; confirmation is manual. Marqa charges no fee on invoices.",
  "Cadastre sua chave Pix em Configurações": "Add your Pix key in Settings",
  "Descrição": "Description",
  "Valor": "Amount",
  "Vencimento": "Due date",
  "+ Linha": "+ Line",
  "Salvar": "Save",
  "Recebimentos (Pix)": "Payments (Pix)",
  "As faturas dos clientes saem com Pix copia e cola e QR da sua chave. O pagamento cai direto na sua conta — a Marqa não passa o dinheiro nem cobra taxa. A confirmação do pagamento é sua.":
    "Client invoices go out with a Pix copy-and-paste code and QR for your key. The payment lands straight in your account — Marqa never handles the money or charges a fee. You confirm each payment.",
  "Chave Pix": "Pix key",
  "CNPJ, CPF, e-mail, celular ou chave aleatória": "CNPJ, CPF, email, mobile or random key",
  "Nome de quem recebe": "Recipient name",
  "Como aparece no banco": "As it appears at the bank",
  "Cidade": "City",
  "Dia do vencimento": "Due day",
  "Aviso de atraso (opcional)": "Late notice (optional)",
  "Ex.: após o vencimento, multa de 2% conforme contrato": "E.g.: after the due date, 2% fine as per contract",
  "Salvar recebimentos": "Save payment details",
  "Pronto para enviar faturas": "Ready to send invoices",
  "Faltam dados para enviar faturas": "Details missing to send invoices",
  "Financeiro": "Billing",
  "Em aberto": "Open",
  "Aguardando confirmação": "Awaiting confirmation",
  "Faturas": "Invoices",
  "Cobranças →": "Billing →",
  "Lembrar": "Remind",
  "Recebido": "Received",
  "Cadastre sua chave Pix em Configurações → Recebimentos.": "Add your Pix key in Settings → Payments.",
  "Envie a fatura primeiro.": "Send the invoice first.",
  "Só dá para editar a fatura antes de enviar.": "An invoice can only be edited before it's sent.",
  "A fatura precisa de pelo menos uma linha.": "The invoice needs at least one line.",
  "Sem fee nem extras neste mês. Defina o fee do cliente em Horas & margem ou adicione uma linha.":
    "No fee or extras this month. Set the client's fee in Hours & margin or add a line.",
  "Chave Pix inválida. Use CPF, CNPJ, e-mail, celular ou chave aleatória.": "Invalid Pix key. Use CPF, CNPJ, email, mobile or a random key.",
  "Confira os dados de recebimento.": "Check the payment details.",
  "Escolha o cliente e o mês.": "Choose the client and the month.",
  // Assinatura no cartão
  "Assinatura enviada ao Mercado Pago. O plano liga assim que a primeira cobrança no cartão for aprovada.":
    "Subscription sent to Mercado Pago. The plan turns on as soon as the first card charge is approved.",
  "Preços em reais (R$), cobrados pelo Mercado Pago.": "Prices in Brazilian reais (R$), billed in BRL by Mercado Pago.",
  "Assinatura no cartão: renova sozinha no período escolhido; cancele quando quiser e o plano vale até o fim do período pago. Ou pague um período à vista (Pix, boleto ou cartão), sem renovação.":
    "Card subscription: renews on its own for the period you pick; cancel anytime and the plan lasts until the end of the paid period. Or pay one period up front (Pix, boleto or card), with no renewal.",
  "Os planos são pagos por período (Pix, cartão ou boleto) e não renovam sozinhos: no fim do período a conta volta para o grátis.":
    "Plans are paid per period (Pix, card or boleto) and don't renew on their own: at the end of the period the account goes back to free.",
  "Arrependimento em até 7 dias —": "7-day cooling-off period —",
  "Assinatura no cartão (Mercado Pago)": "Card subscription (Mercado Pago)",
  "Cancelar renovação": "Cancel renewal",
  "Cancelar a renovação no cartão? Seu plano continua até o fim do período já pago.": "Cancel the card renewal? Your plan continues until the end of the period already paid.",
  "Qual e-mail você usa no Mercado Pago? A assinatura fica ligada a ele.": "Which email do you use on Mercado Pago? The subscription is linked to it.",
  "E-mail do Mercado Pago": "Mercado Pago email",
  "Assinar no cartão · mensal": "Subscribe by card · monthly",
  "Pagar o período à vista (Pix/boleto)": "Pay the period up front (Pix/boleto)",
  "Informe o e-mail da conta do Mercado Pago.": "Enter the email of your Mercado Pago account.",
  "Não foi possível abrir a assinatura agora. Tente de novo em instantes.": "We couldn't open the subscription right now. Try again shortly.",
  "Não há assinatura no cartão para cancelar.": "There's no card subscription to cancel.",
  "Não conseguimos cancelar no Mercado Pago agora. Tente de novo em instantes.": "We couldn't cancel on Mercado Pago right now. Try again shortly.",
  // Carrosséis
  "Carrosséis": "Carousels",
  "Carrossel pronto para postar": "Ready-to-post carousel",
  "A IA escreve de 5 a 8 slides no tom da marca e a Marqa monta as imagens (1080×1350) com as cores e o logo do cliente. Baixe o ZIP ou mande para o calendário.":
    "The AI writes 5 to 8 slides in the brand's voice and Marqa builds the images (1080×1350) with the client's colours and logo. Download the ZIP or send it to the calendar.",
  "Tema": "Topic",
  "Ex.: 5 erros ao escolher um café especial": "E.g.: 5 mistakes when choosing specialty coffee",
  "Objetivo (opcional)": "Goal (optional)",
  "Ex.: salvar o post e pedir pelo direct": "E.g.: save the post and order by DM",
  "Slides": "Slides",
  "Modelo visual": "Visual template",
  "Escrevendo os slides...": "Writing the slides...",
  "Gerar com IA · 3 coins": "Generate with AI · 3 coins",
  "Escrever eu mesmo": "Write it myself",
  "A IA não está disponível agora: escreva os slides e as imagens saem igual.": "AI isn't available right now: write the slides and the images come out just the same.",
  "Dica: suba o logo em Briefing → Arquivos da marca (com \"logo\" no nome).": "Tip: upload the logo in Briefing → Brand files (with \"logo\" in the name).",
  "Nenhum carrossel ainda. Escolha um tema acima — carrosséis foram o formato com mais engajamento no Instagram em 2026.":
    "No carousels yet. Pick a topic above — carousels were Instagram's most engaging format in 2026.",
  "Mesmo pedido de antes: veio do histórico, sem gastar coins.": "Same request as before: it came from history, no coins spent.",
  "Carrossel criado. Ajuste o texto de qualquer slide e a imagem se atualiza sozinha.": "Carousel created. Edit any slide's text and its image updates on its own.",
  "exemplo (modo de teste)": "example (test mode)",
  "Baixar tudo (ZIP)": "Download all (ZIP)",
  "Excluir": "Delete",
  "Excluir este carrossel?": "Delete this carousel?",
  "Baixar": "Download",
  "Legenda": "Caption",
  "Salvar textos": "Save texts",
  "Postar em": "Post on",
  "Levar para o calendário": "Send to the calendar",
  "Atualizar no calendário": "Update in the calendar",
  "No calendário como rascunho ✓": "In the calendar as a draft ✓",
  "Transformar em carrossel": "Turn into a carousel",
  "Informe o tema e de 5 a 8 slides.": "Enter the topic and 5 to 8 slides.",
  "A IA não está disponível agora. Escreva os slides à mão.": "AI isn't available right now. Write the slides by hand.",
  "O carrossel precisa de pelo menos 5 slides.": "The carousel needs at least 5 slides.",
  "Todo slide precisa de um título.": "Every slide needs a title.",
  "Escolha a data e a hora.": "Pick the date and time.",
  // Briefing falado (troca de turno automática)
  "Me conta da marca: como se chama, o que vende, quem compra e o que você quer que o marketing alcance. Quando você parar de falar, é a minha vez.":
    "Tell me about the brand: what it's called, what it sells, who buys it and what you want marketing to achieve. When you stop talking, it's my turn.",
  "Ouvindo…": "Listening…",
  "Pensando…": "Thinking…",
  "Falando…": "Speaking…",
  "Quando você parar de falar, a IA entende que é a vez dela.": "When you stop talking, the AI knows it's its turn.",
  "Terminei de falar": "I'm done talking",
  "Interromper e falar": "Interrupt and talk",
  "Começar a falar": "Start talking",
  "Falar mais": "Say more",
  "Seu navegador não suporta voz — use Chrome, Edge ou Safari. Você pode digitar o briefing.":
    "Your browser doesn't support voice — use Chrome, Edge or Safari. You can type the briefing.",
  "Digitar o briefing": "Type the briefing",
  "Chegamos ao limite de conversa deste briefing. Revise os campos ou complete digitando.":
    "This briefing has reached its conversation limit. Review the fields or finish by typing.",
  "Não consegui abrir o microfone. Libere o acesso ou digite o briefing.": "I couldn't open the microphone. Allow access or type the briefing.",
  "Salvar no briefing": "Save to the briefing",
  "Como prefere contar sobre sua marca?": "How would you like to tell us about your brand?",
  "Fale como numa conversa: quando você para, a IA entende que é a vez dela e pergunta o que faltar.":
    "Talk like in a conversation: when you pause, the AI knows it's its turn and asks for whatever is missing.",
  "Falando": "Talking",
  "Escrevendo": "Writing",
  "Briefing salvo. Confira os campos na aba Briefing quando quiser.": "Briefing saved. Check the fields in the Briefing tab whenever you like.",
  // Links & bio
  "Link na bio": "Link in bio",
  "Links & bio": "Links & bio",
  "Link curto com UTM em cada post e uma página de link na bio por cliente. Você vê o que dá clique.":
    "A short link with UTM on every post and a link-in-bio page per client. You see what gets clicks.",
  "Ver links": "View links",
  "Links curtos com UTM automático e a página de link na bio de cada cliente. Os cliques entram no relatório mensal.":
    "Short links with automatic UTM and each client's link-in-bio page. Clicks go into the monthly report.",
  "Cadastre um cliente para criar os primeiros links.": "Add a client to create the first links.",
  "Cliques (30 dias)": "Clicks (30 days)",
  "não publicada": "not published",
  "Links rastreáveis": "Tracked links",
  "Cole o endereço: a Marqa cria um link curto com UTM e conta os cliques (sem cookie). Nos posts do calendário, use o campo Link.":
    "Paste the address: Marqa creates a short link with UTM and counts clicks (no cookies). On calendar posts, use the Link field.",
  "Endereço de destino": "Destination address",
  "Nome do botão": "Button name",
  "Ver a loja": "Visit the shop",
  "Criar": "Create",
  "Nenhum link ainda.": "No links yet.",
  "de um post do calendário": "from a calendar post",
  "+ na bio": "+ to bio",
  "Arquivar": "Archive",
  "Uma página com as cores e o logo da marca, os botões e os últimos posts publicados. Cada toque conta como clique.":
    "A page with the brand's colours and logo, the buttons and the latest published posts. Every tap counts as a click.",
  "Endereço": "Address",
  "Título": "Title",
  "Texto curto": "Short text",
  "O que a marca faz, em uma frase.": "What the brand does, in one sentence.",
  "Botões (até 8)": "Buttons (up to 8)",
  "Crie um link ao lado para virar botão.": "Create a link on the side to turn it into a button.",
  "Texto do botão": "Button text",
  "Subir": "Move up",
  "Descer": "Move down",
  "Tirar da bio": "Remove from bio",
  "Página no ar": "Page live",
  "Aparecer no Google": "Show on Google",
  "Salvar página": "Save page",
  "Abrir a página ↗": "Open the page ↗",
  "Copiar endereço": "Copy address",
  "Criar link rastreável": "Create a tracked link",
  "Links e bio": "Links and bio",
  "Crie links com UTM automático e uma página de link na bio. Os cliques entram no relatório e no \"o que funciona\".":
    "Create links with automatic UTM and a link-in-bio page. Clicks go into the report and into \"what works\".",
  "Link": "Link",
  "Rastrear": "Track",
  "Inserir na legenda": "Add to caption",
  "Links mais clicados": "Most clicked links",
  "Cliques nos links rastreáveis da marca (sem robôs, sem cookies).": "Clicks on the brand's tracked links (no bots, no cookies).",
  "Cliques nos links dos posts": "Clicks on post links",
  "Últimos posts": "Latest posts",
  "Em breve.": "Coming soon.",
  "Escolha um endereço com pelo menos 3 letras.": "Pick an address with at least 3 letters.",
  "Este endereço é reservado. Escolha outro.": "This address is reserved. Pick another one.",
  "Este endereço já está em uso. Escolha outro.": "This address is already taken. Pick another one.",
  "Informe um endereço válido (http ou https).": "Enter a valid address (http or https).",
  "Só aceitamos endereços http ou https.": "Only http or https addresses are accepted.",
  // Radar de IA
  "Radar de IA": "AI radar",
  "Quando alguém pergunta para uma IA, seus clientes aparecem? Um relatório para revender todo mês.":
    "When someone asks an AI, do your clients show up? A report you can resell every month.",
  "Abrir o radar": "Open the radar",
  "Nenhum radar rodado ainda": "No radar run yet",
  "Quando alguém pergunta para uma IA, seus clientes aparecem? Simulação com busca na web, uma vez por semana por cliente — um entregável para vender todo mês.":
    "When someone asks an AI, do your clients show up? A simulation with web search, once a week per client — a deliverable to sell every month.",
  "Cadastre um cliente para montar o primeiro radar.": "Add a client to set up the first radar.",
  "Perguntas": "Questions",
  "Participação": "Share",
  "Última rodada": "Last run",
  "nunca": "never",
  "+ Pergunta": "+ Question",
  "Remover pergunta": "Remove question",
  "Pensando nas perguntas...": "Thinking of questions...",
  "Sugerir perguntas com IA (1 coin)": "Suggest questions with AI (1 coin)",
  "Salvar perguntas": "Save questions",
  "Perguntando para a IA (1-3 min)...": "Asking the AI (1-3 min)...",
  "A IA não está disponível agora. Abaixo, um exemplo do que o radar mostra.": "AI isn't available right now. Below is an example of what the radar shows.",
  "Salve as perguntas e rode o radar. Ele roda uma vez por semana por cliente.": "Save the questions and run the radar. It runs once a week per client.",
  "exemplo — sem IA agora": "example — no AI right now",
  "Participação da marca": "Brand share of voice",
  "Respostas que citam a marca": "Answers that cite the brand",
  "Concorrentes citados": "Competitors cited",
  "Cadastre concorrentes no briefing ou na estratégia.": "Add competitors in the briefing or the strategy.",
  "Por que não você": "Why not you",
  "O que fazer agora": "What to do now",
  "Pergunta por pergunta": "Question by question",
  "Pergunta": "Question",
  "Marcas citadas": "Brands cited",
  "A marca aparece?": "Does the brand show up?",
  "Sim": "Yes",
  "Não": "No",
  "Simulação feita por IA com busca na web. Assistentes como ChatGPT e Gemini podem responder diferente.":
    "AI simulation with web search. Assistants like ChatGPT and Gemini may answer differently.",
  "Salve pelo menos uma pergunta antes de rodar.": "Save at least one question before running.",
  "Até 10 perguntas.": "Up to 10 questions.",
  "A IA não está disponível agora. Escreva as perguntas.": "AI isn't available right now. Write the questions.",
  "Peça avaliações no Google e responda todas — é o que os assistentes mais leem.": "Ask for Google reviews and answer every one — assistants read them most.",
  "Deixe claro no site o que você vende, onde atende e para quem — com perguntas e respostas.": "Make your site state clearly what you sell, where and for whom — with an FAQ.",
  "Complete o perfil no Google Maps e nos diretórios do setor com o mesmo nome e endereço.": "Complete your Google Maps and industry directory profiles with the same name and address.",
  "Conte uma novidade para a imprensa local: matérias viram fonte para a IA.": "Pitch a story to local press: articles become sources for AI.",
  "Publique com frequência respondendo às perguntas que as pessoas fazem.": "Post regularly answering the questions people actually ask.",
  "Publique no site respostas claras para as perguntas dos seus clientes.": "Publish clear answers to your customers' questions on your site.",
  // Painel de público
  "Testar com o público": "Test with the audience",
  "Testar o gancho (slide 1) com o público": "Test the hook (slide 1) with the audience",
  "Painel de público (simulação)": "Audience panel (simulation)",
  "+ Versão C": "+ Version C",
  "O painel está lendo...": "The panel is reading...",
  "Testar · 2 coins": "Test · 2 coins",
  "personas genéricas (sem estratégia)": "generic personas (no strategy yet)",
  "mesmo teste de antes — sem custo": "same test as before — no cost",
  "Persona": "Persona",
  "Média": "Average",
  "Usar a vencedora": "Use the winner",
  "Simulação com personas da estratégia — serve pra descartar opções fracas, não substitui teste real. Depois, os cliques reais dizem se o painel acertou.":
    "A simulation with the strategy's personas — good for ruling out weak options, not a replacement for a real test. Later, real clicks show whether the panel was right.",
  "Painel de público: ainda sem dados suficientes para saber se ele acerta (precisa de 5 testes que foram ao ar).":
    "Audience panel: not enough data yet to know if it's right (needs 5 tests that went live).",
  "Teste de 2 a 3 variantes.": "Test 2 to 3 variants.",
  "Cada variante precisa de 3 a 2.200 caracteres.": "Each variant needs 3 to 2,200 characters.",
  "As variantes precisam ser diferentes.": "The variants must be different.",
  "Desconfiada de primeira vez": "Skeptical first-timer",
  "Cliente fiel": "Loyal regular",
  "Rolagem apressada": "Busy scroller",
  "Caçador de preço": "Price hunter",
  // Rodada 3 — tours por papel, primeiros passos e diferenciais
  "Aprovar": "Approve",
  "Digite ou fale o briefing.": "Type or say the briefing.",
  "Sua central: o que precisa de decisão agora — candidaturas, entregas para revisar, aprovações paradas, posts na hora.":
    "Your hub: what needs a decision now — applications, deliveries to review, stalled approvals, posts due.",
  "Cada cliente tem briefing, kit de IA (estratégia, campanhas, identidade, social), pacote do mês, demandas e portal próprio.":
    "Every client has a briefing, an AI kit (strategy, campaigns, identity, social), a monthly package, jobs and their own portal.",
  "Aqui você pode falar em vez de digitar: a IA escuta, pergunta o que faltar e preenche o cadastro para você revisar.":
    "Here you can talk instead of typing: the AI listens, asks what's missing and fills in the form for you to review.",
  "Demandas em kanban: da abertura ao pagamento, com freelancers ou equipe interna.":
    "Jobs on a kanban board: from brief to payment, with freelancers or your in-house team.",
  "Insights, horas e margem por cliente e as cobranças Pix do mês num lugar só.":
    "Insights, hours and margin per client, and this month's Pix invoices in one place.",
  "Escopo e fatura": "Scope and invoicing",
  "Defina o pacote de cada cliente. Extra só entra com valor aprovado — e vai pra fatura Pix do mês.":
    "Set each client's package. Extras only happen with an approved price — and go on the month's Pix invoice.",
  "No calendário, selecione os posts e toque em Enviar para aprovação. O cliente abre no celular, sem senha, aprova ou pede ajuste — e o histórico fica guardado.":
    "In the calendar, pick the posts and tap Send for approval. The client opens it on their phone, no password, approves or asks for changes — and the history is kept.",
  "Fatura Pix sem taxa": "Pix invoices, no fees",
  "Em Resultados → Cobranças: a fatura sai com QR Pix da sua chave e lembrete pronto pro WhatsApp. O dinheiro cai direto na sua conta; você só confirma.":
    "In Results → Invoices: each invoice comes with a Pix QR for your own key and a ready WhatsApp reminder. The money lands straight in your account; you just confirm.",
  "Carrossel pronto": "Ready-to-post carousels",
  "Na aba Carrosséis de cada cliente (ou a partir de um post), a IA escreve os slides e eles saem com as cores e o logo da marca. Baixe as imagens ou agende.":
    "In each client's Carousels tab (or from a post), the AI writes the slides and they come out in the brand's colors and logo. Download the images or schedule them.",
  "Link na bio e cliques": "Link in bio and clicks",
  "Cada cliente ganha uma página de links e links curtos por post. Você vê quais posts levam gente pro site — sem cookies.":
    "Every client gets a links page and short links per post. You see which posts send people to the site — no cookies.",
  "Quando alguém pergunta pra uma IA pelo melhor negócio do ramo, seu cliente aparece? Uma rodada por semana mostra quem é citado e o que fazer.":
    "When someone asks an AI for the best business in the field, does your client show up? A weekly run shows who gets cited and what to do.",
  "Teste com o público": "Test with the audience",
  "Antes de agendar, compare 2 ou 3 versões do texto com as personas da estratégia. É uma simulação para descartar opções fracas; os cliques reais dizem se acertou.":
    "Before scheduling, compare 2 or 3 versions of the copy with the strategy's personas. It's a simulation to rule out weak options; real clicks tell you if it was right.",
  "Em Crescimento → Prospecção, cada prospect ganha uma página com pitch, pacotes e prazo. Ele aceita sem login e já vira cliente com acesso ao portal.":
    "In Growth → Prospecting, every prospect gets a page with the pitch, packages and deadline. They accept without logging in and become a client with portal access.",
  "No portal, o cliente responde 😞😐😀 depois de cada aprovação e uma vez por mês, e o NPS a cada trimestre. A Hoje mostra quem está em risco e o relatório mensal traz os números.":
    "In the portal, the client answers 😞😐😀 after each approval and once a month, plus NPS every quarter. Today shows who's at risk and the monthly report has the numbers.",
  "Na aba Horas de cada cliente você aponta tempo por demanda. Em Horas & margem, cada cliente aparece com fee, horas, custo, recebido e margem do mês — quem dá prejuízo fica em vermelho.":
    "In each client's Hours tab you log time per job. In Hours & margin, every client shows fee, hours, cost, received and the month's margin — the ones losing money turn red.",
  "No calendário e no atendente, o botão Checar voz da marca compara o texto com o briefing e as regras do cliente e dá uma nota de tom. Reescrever no tom corrige em 1 clique.":
    "In the calendar and the attendant, the Check brand voice button compares the copy with the client's briefing and rules and gives a tone score. Rewrite in tone fixes it in 1 click.",
  "Na aba 30 dias de cada cliente: objetivo, canais e data de início. A IA planeja as semanas e escreve cada post; tudo entra no calendário como rascunho nos dias livres.":
    "In each client's 30 days tab: goal, channels and start date. The AI plans the weeks and writes every post; everything goes into the calendar as drafts on free days.",
  "No Dashboard de cada cliente, os posts publicados são cruzados com vendas, métricas e cliques dos dias seguintes: melhor formato, dia e horário e o que menos rende.":
    "On each client's Dashboard, published posts are matched against the following days' sales, metrics and clicks: best format, day and time, and what performs worst.",
  "Conte falando": "Say it out loud",
  "Toque em Falando e responda como numa conversa. Quando você para, a IA entende que é a vez dela.":
    "Tap Talking and answer like in a conversation. When you stop, the AI knows it's its turn.",
  "Gere o seu kit": "Generate your kit",
  "Estratégia, campanha, identidade e ROI saem do seu briefing. O Kit completo faz tudo de uma vez.":
    "Strategy, campaign, identity and ROI come from your briefing. The Full kit does it all at once.",
  "Um mês de posts": "A month of posts",
  "Escolha o objetivo e a IA escreve 30 dias de posts direto no calendário. Você aceita ou pula um a um.":
    "Pick the goal and the AI writes 30 days of posts straight into the calendar. You accept or skip them one by one.",
  "Da ideia ao carrossel com as cores e o logo da marca. É só baixar e postar.":
    "From idea to carousel in the brand's colors and logo. Just download and post.",
  "O que funcionou": "What worked",
  "Todo mês, um relatório com posts, cliques e vendas — e o que funciona pra sua marca.":
    "Every month, a report with posts, clicks and sales — and what works for your brand.",
  "Chegou um link? É só abrir, olhar e tocar em Aprovar. Pediu ajuste, a agência recebe na hora. Aqui no portal fica tudo o que está em produção.":
    "Got a link? Just open it, look and tap Approve. Ask for changes and the agency gets it right away. Everything in production is here in the portal.",
  "Seu pacote do mês": "Your monthly package",
  "Veja quanto do pacote já foi usado e peça uma produção. Se passar do combinado, o valor do extra chega para você aprovar antes.":
    "See how much of the package is used and request new work. If it goes beyond the deal, the extra's price comes to you to approve first.",
  "As faturas da agência ficam aqui, com Pix copia e cola. Pagou? Toque em Já paguei e a agência confirma.":
    "The agency's invoices are here, with Pix copy-and-paste. Paid? Tap I've paid and the agency confirms.",
  "Mande mensagem para a agência e conte como está sendo — sua nota ajuda o time a melhorar.":
    "Message the agency and tell them how it's going — your rating helps the team improve.",
  "Portfólio": "Portfolio",
  "Suba pelo menos 3 trabalhos. É isso que o match da IA olha antes de indicar você.":
    "Upload at least 3 pieces. That's what the AI match looks at before recommending you.",
  "As demandas abertas na plataforma aparecem aqui, com verba e prazo.":
    "Open jobs on the platform show up here, with budget and deadline.",
  "Candidatura": "Applying",
  "Toque em Candidatar-se e mande uma mensagem curta. O status da candidatura fica ao lado da demanda.":
    "Tap Apply and send a short message. The application status sits next to the job.",
  "Entrega com marcações": "Deliveries with markup",
  "Aceita, a demanda aparece em Minhas demandas. Suba a entrega; a agência revisa com marcações direto na imagem.":
    "Once accepted, the job shows up in My jobs. Upload the delivery; the agency reviews it with notes right on the image.",
  "Ganhos e elo": "Earnings and tier",
  "Veja o que tem a receber e o que já foi pago. Entregas bem avaliadas sobem o seu elo — e a sua visibilidade.":
    "See what you're owed and what's been paid. Well-rated deliveries raise your tier — and your visibility.",
  "Ver todos os diferenciais": "See every differentiator",
  "Refazer tour": "Replay the tour",
  "Primeiros passos concluídos": "First steps done",
  "Tudo pronto — você já usou o essencial.": "All set — you've used the essentials.",
  "Progresso dos primeiros passos": "First steps progress",
  "Falando ou escrevendo: é daqui que a IA tira tudo.":
    "Talking or typing: this is where the AI gets everything.",
  "Gere a primeira peça com IA": "Generate your first AI piece",
  "Estratégia, calendário ou posts.": "Strategy, calendar or posts.",
  "Coloque um post na agenda": "Put a post on the calendar",
  "Use os 30 dias ou crie à mão.": "Use the 30 days or create one by hand.",
  "Monte um carrossel": "Build a carousel",
  "Pronto para baixar e postar.": "Ready to download and post.",
  "Veja o que funcionou": "See what worked",
  "Relatório do mês com os números da marca.": "The month's report with the brand's numbers.",
  "Aprove uma peça": "Approve a piece",
  "Pelo portal ou pelo link que a agência mandar.": "In the portal or through the link the agency sends.",
  "Peça uma produção": "Request new work",
  "O pacote do mês mostra o que já foi usado e o que vira extra.":
    "The monthly package shows what's used and what becomes an extra.",
  "Abra uma fatura": "Open an invoice",
  "Pix direto para a agência, com copia e cola.": "Pix straight to the agency, with copy-and-paste.",
  "Uma mensagem ou a nota de como está sendo.": "A message or a rating of how it's going.",
  "Complete o perfil": "Complete your profile",
  "Bio, habilidades e cidade.": "Bio, skills and city.",
  "Suba 3 trabalhos": "Upload 3 pieces",
  "É isso que o match da IA olha antes de indicar você.":
    "That's what the AI match looks at before recommending you.",
  "Candidate-se a uma demanda": "Apply for a job",
  "Uma mensagem curta basta.": "A short message is enough.",
  "Faça a primeira entrega": "Make your first delivery",
  "A agência revisa com marcações na imagem.": "The agency reviews it with notes on the image.",
  "Nome, cor e logo no portal dos clientes.": "Name, color and logo on your clients' portal.",
  "Defina o pacote de um cliente": "Set a client's package",
  "Extra só entra com valor aprovado.": "Extras only happen with an approved price.",
  "Receba pedidos pelo seu endereço.": "Get requests at your own address.",
  "Cada convite entra direto no seu espaço.": "Every invite goes straight into your workspace.",
  "Conclua os primeiros passos antes de fechar.": "Finish the first steps before closing.",
  "Não deu para fechar agora.": "Couldn't close it right now.",
  "Pacote e escopo sob controle": "Scope that counts itself",
  "Defina o pacote de cada cliente: cada post é contado, você é avisado quando passa e o extra vira valor aprovado.":
    "Set each client's package: every post is counted, you're warned when it runs over and extras become an approved price.",
  "Definir num cliente": "Set it on a client",
  "O cliente aprova pelo WhatsApp, sem senha. O post aprovado já fica marcado na agenda, com histórico.":
    "Clients approve from a WhatsApp link — no password. The approved post is marked on the calendar, with history.",
  "Enviar posts para aprovar": "Send posts for approval",
  "Fatura do fee com QR Pix da sua chave e lembrete pronto. O dinheiro cai direto na sua conta.":
    "Fee invoices with a Pix QR for your own key and a ready reminder. The money lands straight in your account.",
  "Abrir cobranças": "Open invoices",
  "Da ideia ao carrossel com as cores e o logo do cliente — é só baixar e postar, ou agendar.":
    "Carousels in the brand's look, ready to post — download, post or schedule.",
  "Criar num cliente": "Create one on a client",
  "Página de links por cliente e links curtos por post: você vê o que leva gente pro site, sem cookies.":
    "A links page per client and short links per post: see what sends people to the site, no cookies.",
  "Quando alguém pergunta pra uma IA, seu cliente aparece? Quem é citado e o que fazer para aparecer mais.":
    "When someone asks an AI, does your client show up? Who gets cited and what to do to show up more.",
  "Abrir radar": "Open radar",
  "Compare versões do texto com as personas da estratégia antes de agendar. Simulação para descartar o fraco.":
    "Compare versions of the copy with the strategy's personas before scheduling. A simulation to rule out the weak ones.",
  "Testar um post": "Test a post",
  "Mostrar menos": "Show less",
  "Bem-vindo ao seu portal": "Welcome to your portal",
  "Aprove sem complicação": "Approve without the hassle",
  "A agência manda as peças por aqui ou por um link no WhatsApp. Você olha, aprova ou pede ajuste.":
    "The agency sends pieces here or through a WhatsApp link. You look, approve or ask for changes.",
  "Veja o que já foi produzido e peça novas produções. Extra só entra com valor aprovado por você.":
    "See what's been produced and request new work. Extras only happen with a price you approve.",
  "Mensagens, faturas com Pix e o relatório do mês ficam no mesmo lugar.":
    "Messages, Pix invoices and the monthly report, all in one place.",
  "Nenhuma fatura por aqui ainda. Quando a agência enviar, ela aparece aqui com Pix copia e cola.":
    "No invoices here yet. When the agency sends one, it shows up here with Pix copy-and-paste.",
  // Rodada 3 · correções de lançamento (aprovação x agendador, escopo, primeiros passos)
  "Não vai ao ar enquanto o cliente não aprovar pelo link.": "It won't go live until the client approves it through the link.",
  "Não vai ao ar até o cliente aprovar a versão nova. Ajuste e mande outro link.":
    "It won't go live until the client approves the new version. Make the change and send another link.",
  "Liberar sem aprovação": "Release without approval",
  "O cliente escolheu este item; confira se o pedido é mesmo do pacote.":
    "The client picked this item; check whether the request really belongs to the package.",
  "Cobrar como extra": "Charge as an extra",
  "Pode fechar quando quiser; os passos continuam marcando sozinhos.":
    "You can close this whenever you like; the steps keep ticking on their own.",
  "Ocultar": "Hide",
};

export const UI_REGEX_R3: [RegExp, string][] = [
  [/^(\d+) de (\d+)$/, "$1 of $2"],
  [
    /^Não conseguimos publicar: (.+)\. Confira a conexão e agende de novo para tentar outra vez\.$/,
    "We couldn't publish it: $1. Check the connection and schedule it again to retry.",
  ],
  [/^Ver todos os diferenciais \((\d+)\)$/, "See every differentiator ($1)"],
  [/^Versão ([ABC])$/, "Version $1"],
  [/^Vencedora: versão ([ABC])$/, "Winner: version $1"],
  [/^Ajuste sugerido: (.+)$/, "Suggested fix: $1"],
  [/^para (\d+)\/10 · clareza (\d+)\/10 · clicaria$/, "stops $1/10 · clarity $2/10 · would click"],
  [/^para (\d+)\/10 · clareza (\d+)\/10 · não clicaria$/, "stops $1/10 · clarity $2/10 · wouldn't click"],
  [/^([\d.]+) · (\d+)% clicariam$/, "$1 · $2% would click"],
  [/^Versão ([ABC]) no calendário ✓$/, "Version $1 in the calendar ✓"],
  [/^Agendar versão ([ABC]) para comparar$/, "Schedule version $1 to compare"],
  [/^Painel de público: acertou (\d+) de (\d+) testes que foram ao ar \((\d+)%\)\.$/, "Audience panel: right in $1 of $2 tests that went live ($3%)."],
  [/^Quando alguém pergunta para uma IA "qual o melhor (.+) perto de mim\?", (.+) aparece\? A IA faz as perguntas com busca na web, anota quem é citado e o que fazer para aparecer mais\.$/, "When someone asks an AI \"what's the best $1 near me?\", does $2 show up? The AI asks with web search, notes who gets cited and what to do to show up more."],
  [/^Perguntas de quem compra \(até (\d+)\)$/, "Buyer questions (up to $1)"],
  [/^Rodar radar · (\d+) coins$/, "Run radar · $1 coins"],
  [/^Próxima rodada a partir de (.+)$/, "Next run from $1"],
  [/^([+-]?[\d.,]+) p\.p\. desde a rodada anterior$/, "$1 pts since the previous run"],
  [/^melhor posição: (\d+)º$/, "best position: #$1"],
  [/^(\d+) de (\d+) respostas citam (.+)$/, "$1 of $2 answers cite $3"],
  [/^Pergunta (\d+)$/, "Question $1"],
  [/^Simulação feita por IA com busca na web em (.+)\. Assistentes como ChatGPT e Gemini podem responder diferente\.$/, "AI simulation with web search on $1. Assistants like ChatGPT and Gemini may answer differently."],
  [/^O radar deste cliente roda uma vez por semana\. Próxima rodada a partir de (.+)\.$/, "This client's radar runs once a week. Next run from $1."],
  [/^(\d+) cliente\(s\) com radar$/, "$1 client(s) with a radar"],
  [/^(\d+) cliques · (\d+) pessoas \(30 dias\)$/, "$1 clicks · $2 people (30 days)"],
  [/^(\d+) cliques em 30 dias · (\d+) bio\(s\) no ar$/, "$1 clicks in 30 days · $2 bio page(s) live"],
  [/^(\d+) cliques em (\d+) post\(s\) publicados com link$/, "$1 clicks on $2 published post(s) with a link"],
  [/^(.+): ([\d.]+) cliques por post$/, "$1: $2 clicks per post"],
  [/^· (\d+) clique\(s\)$/, "· $1 click(s)"],
  [/^(\d+)\/(\d+) falas$/, "$1/$2 turns"],
  [/^(\d+) slides · (.+)$/, "$1 slides · $2"],
  [/^Título do slide (\d+)$/, "Slide $1 title"],
  [/^Texto do slide (\d+)$/, "Slide $1 text"],
  [/^Cancelada — o plano vale até (.+) e depois volta para o grátis\.$/, "Canceled — the plan lasts until $1 and then goes back to free."],
  [/^Próxima cobrança em (.+)\. Sem fidelidade: cancele quando quiser\.$/, "Next charge on $1. No lock-in: cancel anytime."],
  [/^Renovação cancelada\. Seu plano vale até (.+)\.$/, "Renewal canceled. Your plan lasts until $1."],
  [/^Assinar no cartão · a cada (\d+) meses$/, "Subscribe by card · every $1 months"],
  [/^Vence (\d{2}\/\d{2}) · (\d+) linha\(s\)$/, "Due $1 · $2 line(s)"],
  [/^· atrasada há (\d+) dia\(s\)$/, "· $1 day(s) overdue"],
  [/^(\d+) fatura\(s\) vencem esta semana · (.+)$/, "$1 invoice(s) due this week · $2"],
  [/^(\d+) cliente\(s\) avisaram que pagaram — confira e confirme$/, "$1 client(s) say they paid — check and confirm"],
  [/^(\d+) rascunho\(s\) esperando envio$/, "$1 draft(s) waiting to be sent"],
  [/^Uso em (.+)$/, "Usage in $1"],
  [/^Pacote de (.+)$/, "$1 package"],
  [/^Seu pacote em (.+):$/, "Your package in $1:"],
  [/^Aprovar extra de (.+)$/, "Approve extra of $1"],
  [/^(\d+) extra\(s\) esperando o cliente aprovar o valor$/, "$1 extra(s) waiting for the client to approve the price"],
  [/^(\d+) pedido\(s\) esperando o cliente aprovar o valor$/, "$1 request(s) waiting for the client to approve the price"],
  [/^Extras aprovados este mês: (.+)$/, "Extras approved this month: $1"],
  [/^Cabe no seu pacote \(sobram (\d+)\)\.$/, "Fits your package ($1 left)."],
  [/^Isso passa do seu pacote: \+(.+)\. A agência só começa depois que você aprovar\.$/, "This goes beyond your package: +$1. The agency only starts once you approve."],
  [/^Gerar link \((\d+)\)$/, "Create link ($1)"],
  [/^(\d+) itens · (\d+) sem resposta · aberto (\d+)x$/, "$1 items · $2 unanswered · opened $3x"],
  [/^· (\d+) sem resposta$/, "· $1 unanswered"],
  [/^Ajuste pedido por (.+)$/, "Changes asked by $1"],
  [/^Teto diário de IA \(US\$\) · hoje (.+) de sem teto próprio$/, "Daily AI cap (US$) · today $1, no cap of its own"],
  [/^Teto diário de IA \(US\$\) · hoje (.+) de (.+)$/, "Daily AI cap (US$) · today $1 of $2"],

  [/^(\d+) prospects salvos$/, "$1 saved prospects"],
  [/^(\d+) em aberto · (\d+) aceitas$/, "$1 open · $2 accepted"],
  [/^Publicada · (\d+) pedidos recebidos$/, "Published · $1 requests received"],
];
