// Dicionário PT→EN da rodada 3 (mesma regra do ui-dict: correspondência exata
// com o texto da interface). Separado só para não inchar o arquivo principal.
export const UI_DICT_R3: Record<string, string> = {
  // Navegação consolidada
  "Crescimento": "Growth",
  "Mais": "More",
  "Conteúdo": "Content",
  "Visão geral": "Overview",
  "Plano": "Plan",
  "Operação": "Operations",
  "Radar do mercado": "Market radar",
  "Insights": "Insights",
  "Propostas": "Proposals",
  "Página pública": "Public page",
  "Navegação": "Navigation",
  "Seções do cliente": "Client sections",
  "Abas da seção": "Section tabs",
  "Aba do workspace": "Workspace tab",
  "Onde a agência encontra cliente novo e vende mais para quem já está com você.":
    "Where your agency finds new clients and sells more to the ones you already have.",
  "A IA procura empresas do seu nicho e região, com motivo e primeira mensagem para cada uma.":
    "The AI finds businesses in your niche and region, each with a reason and a first message.",
  "Buscar prospects": "Find prospects",
  "Nenhum prospect ainda": "No prospects yet",
  "Uma página com pitch, pacotes e prazo. O prospect aceita sem login e já vira cliente.":
    "A page with the pitch, packages and deadline. The prospect accepts without logging in and becomes a client.",
  "Criar proposta": "Create a proposal",
  "Serviços, trabalhos e depoimentos no seu endereço. O formulário vira prospect e avisa você.":
    "Services, work and testimonials at your own address. The form turns into a prospect and alerts you.",
  "Configurar página": "Set up the page",
  "Ainda não publicada": "Not published yet",
  // Admin: custos, teto e LGPD
  "Custos de IA": "AI costs",
  "Margem por conta (30 dias)": "Margin per account (30 days)",
  "Custo por ação e modelo (30 dias)": "Cost per action and model (30 days)",
  "Sem receita nem uso de IA nos últimos 30 dias.": "No revenue or AI usage in the last 30 days.",
  "Nenhum uso de IA registrado.": "No AI usage recorded.",
  "Receita": "Revenue",
  "Custo IA": "AI cost",
  "Margem": "Margin",
  "Chamadas": "Calls",
  "Buscas": "Searches",
  "Ação": "Action",
  "Modelo": "Model",
  "Salvar teto": "Save cap",
  "Teto de IA salvo.": "AI cap saved.",
  "vazio = padrão do plano": "empty = plan default",
  "Dados pessoais (LGPD)": "Personal data (LGPD)",
  "Exportar dados da conta": "Export account data",
  "Excluir conta": "Delete account",
  "Para excluir, digite": "To delete, type",
  "Conta excluída. Lançamentos financeiros ficam sem vínculo pessoal.": "Account deleted. Financial records stay without any personal link.",
  "A exclusão apaga a conta e o que é só dela; pagamentos e custos ficam para a contabilidade, sem vínculo com a pessoa.":
    "Deleting removes the account and what belongs only to it; payments and costs stay for accounting, with no link to the person.",
  "Escreva o motivo da concessão.": "Write the reason for the grant.",
  "Digite o nome de usuário exato para confirmar.": "Type the exact username to confirm.",
  "Use Minha conta para excluir a própria conta.": "Use My account to delete your own account.",
  "Esta conta não usa IA.": "This account doesn't use AI.",
  // Aprovação por link
  "Enviar para aprovação": "Send for approval",
  "Aprovação por link": "Approval by link",
  "Mande posts e entregas pelo WhatsApp. O cliente aprova sem senha e o post já entra na agenda.":
    "Send posts and deliveries over WhatsApp. The client approves without a password and the post goes straight into the schedule.",
  "O cliente aprova pelo celular, sem login. O post aprovado já entra na agenda.":
    "The client approves from their phone, no login. An approved post goes straight into the schedule.",
  "Link pronto. O cliente abre no celular e aprova sem senha.": "Link ready. The client opens it on their phone and approves without a password.",
  "Enviar no WhatsApp": "Send on WhatsApp",
  "Copiar link": "Copy link",
  "Copiar mensagem": "Copy message",
  "Em reunião? O cliente aponta a câmera e abre direto.": "In a meeting? The client points their camera and it opens.",
  "O que vai para aprovação": "What goes for approval",
  "Nada pendente: crie posts no calendário ou suba entregas nas demandas deste cliente.":
    "Nothing pending: create posts in the calendar or upload deliveries in this client's jobs.",
  "Entrega": "Delivery",
  "Validade": "Valid for",
  "WhatsApp do cliente (opcional)": "Client's WhatsApp (optional)",
  "Gerando...": "Generating...",
  "Links enviados": "Links sent",
  "Aberto": "Open",
  "Expirado": "Expired",
  "Encerrado": "Closed",
  "Reenviar": "Resend",
  "Encerrar": "Close",
  "Encerrar este link? O cliente passa a ver que ele expirou.": "Close this link? The client will see that it has expired.",
  "Cadastre um cliente primeiro.": "Add a client first.",
  "Aguardando o cliente": "Waiting for the client",
  "Aprovado pelo cliente": "Approved by the client",
  "Cliente pediu ajuste": "Client asked for changes",
  "Ajuste pedido pelo cliente": "Changes asked by the client",
  "Pelo link de aprovação": "Through the approval link",
  "⏳ Aguardando aprovação há mais de 48h": "⏳ Waiting for approval for over 48h",
  "3 dias": "3 days",
  "7 dias": "7 days",
  "14 dias": "14 days",
  "30 dias": "30 days",
  "Escolha pelo menos um item.": "Pick at least one item.",
  "Escolha pelo menos um post ou entrega.": "Pick at least one post or delivery.",
  "Algum item não é deste cliente ou já foi publicado.": "Some item isn't from this client or was already published.",
  // Pacote do cliente + escopo
  "Pacote": "Package",
  "Pacote do cliente": "Client package",
  "Ver pacote": "View package",
  "Definir pacote": "Set up package",
  "Diga o que o fee cobre por mês. Pedido fora do combinado vira extra com valor aprovado pelo cliente.":
    "Say what the monthly fee covers. Anything outside it becomes an extra with a price the client approves.",
  "O que o fee cobre por mês": "What the fee covers each month",
  "O cliente vê quanto já usou. Pedido que passa do pacote só vira demanda depois que ele aprova o valor do extra — e o extra entra na fatura do mês.":
    "The client sees how much is used. A request beyond the package only becomes a job after they approve the extra's price — and the extra goes on that month's invoice.",
  "Comece por um modelo e ajuste:": "Start from a template and adjust:",
  "Social básico": "Social basics",
  "Social + tráfego": "Social + ads",
  "Conteúdo premium": "Premium content",
  "Item": "Item",
  "Unidade": "Unit",
  "Por mês": "Per month",
  "Extra (R$/un.)": "Extra (R$/unit)",
  "Remover item": "Remove item",
  "+ Adicionar item": "+ Add item",
  "Novo item": "New item",
  "Acumular o que sobrar para o mês seguinte (um mês)": "Carry what's left over to the next month (one month)",
  "Salvar pacote": "Save package",
  "Sem pacote": "No package",
  "Tirar o pacote deste cliente? Os pedidos voltam a virar demanda direto.": "Remove this client's package? Requests will become jobs directly again.",
  "Defina o pacote para acompanhar o uso.": "Set up the package to track usage.",
  "Pedidos do cliente": "Client requests",
  "Os pedidos feitos no portal aparecem aqui, com o que cabe no pacote e o que é extra.":
    "Requests made in the portal show up here, with what fits the package and what's extra.",
  "Aguardando o cliente aprovar o valor": "Waiting for the client to approve the price",
  "Extra aprovado": "Extra approved",
  "Dentro do pacote": "Within the package",
  "Incluído sem custo": "Included at no cost",
  "Incluir sem custo": "Include at no cost",
  "Cancelar pedido": "Cancel request",
  "posts": "posts",
  "reels": "reels",
  "carrosséis": "carousels",
  "stories": "stories",
  "demandas": "jobs",
  "reuniões": "meetings",
  "relatórios": "reports",
  "Posts no feed": "Feed posts",
  "Peças para anúncio": "Ad creatives",
  "Relatório mensal": "Monthly report",
  "Produções extras (foto, vídeo, arte)": "Extra productions (photo, video, design)",
  "Solicitar uma produção": "Request a production",
  "Precisa de algo? Descreva e a solicitação vira uma demanda no painel da agência na hora.":
    "Need something? Describe it and the request becomes a job on the agency's board right away.",
  "✅ Pedido enviado! Cabe no seu pacote e a agência já recebeu.": "✅ Request sent! It fits your package and the agency already has it.",
  "Esse pedido passa do seu pacote. Aprove o valor abaixo para a agência começar.": "This request goes beyond your package. Approve the price below so the agency can start.",
  "Continuar": "Continue",
  "📋 Enviar solicitação": "📋 Send request",
  "Enviando...": "Sending...",
  "O que é": "What it is",
  "Quantidade": "Quantity",
  "Enviar e ver o valor": "Send and see the price",
  "Enviar pedido": "Send request",
  "Voltar": "Back",
  "💰 Extras do mês": "💰 This month's extras",
  "Os extras aprovados entram na fatura do mês de cada cliente.": "Approved extras go on each client's invoice for the month.",
  "Quem aprova o valor do extra é o cliente.": "Only the client approves the extra's price.",
  "Este pedido já foi decidido.": "This request has already been decided.",
  "Conte o que você precisa.": "Tell us what you need.",
  "Escolha um item do pacote.": "Pick an item from the package.",
  "Confira os itens do pacote.": "Check the package items.",
  "Classificação de exemplo (modo de teste).": "Example classification (test mode).",
};

export const UI_REGEX_R3: [RegExp, string][] = [
  [/^Uso em (.+)$/, "Usage in $1"],
  [/^Pacote de (.+)$/, "$1 package"],
  [/^Seu pacote em (.+):$/, "Your package in $1:"],
  [/^Aprovar extra de (.+)$/, "Approve extra of $1"],
  [/^(\d+) extra\(s\) esperando o cliente aprovar o valor$/, "$1 extra(s) waiting for the client to approve the price"],
  [/^(\d+) pedido\(s\) esperando o cliente aprovar o valor$/, "$1 request(s) waiting for the client to approve the price"],
  [/^Extras aprovados este mês: (.+)$/, "Extras approved this month: $1"],
  [/^Cabe no seu pacote \(sobram (\d+)\)\.$/, "Fits your package ($1 left)."],
  [/^Isso passa do seu pacote: \+(.+)\. A agência só começa depois que você aprovar\.$/, "This goes beyond your package: +$1. The agency only starts once you approve."],
  [/^Gerar link \((\d+)\)$/, "Create link ($1)"],
  [/^(\d+) itens · (\d+) sem resposta · aberto (\d+)x$/, "$1 items · $2 unanswered · opened $3x"],
  [/^· (\d+) sem resposta$/, "· $1 unanswered"],
  [/^Ajuste pedido por (.+)$/, "Changes asked by $1"],
  [/^Teto diário de IA \(US\$\) · hoje (.+) de sem teto próprio$/, "Daily AI cap (US$) · today $1, no cap of its own"],
  [/^Teto diário de IA \(US\$\) · hoje (.+) de (.+)$/, "Daily AI cap (US$) · today $1 of $2"],

  [/^(\d+) prospects salvos$/, "$1 saved prospects"],
  [/^(\d+) em aberto · (\d+) aceitas$/, "$1 open · $2 accepted"],
  [/^Publicada · (\d+) pedidos recebidos$/, "Published · $1 requests received"],
];
