// Dicionário PT→EN da rodada 3 (mesma regra do ui-dict: correspondência exata
// com o texto da interface). Separado só para não inchar o arquivo principal.
export const UI_DICT_R3: Record<string, string> = {
  // Navegação consolidada
  "Crescimento": "Growth",
  "Mais": "More",
  "Conteúdo": "Content",
  "Visão geral": "Overview",
  "Plano": "Plan",
  "Operação": "Operations",
  "Radar do mercado": "Market radar",
  "Insights": "Insights",
  "Propostas": "Proposals",
  "Página pública": "Public page",
  "Navegação": "Navigation",
  "Seções do cliente": "Client sections",
  "Abas da seção": "Section tabs",
  "Aba do workspace": "Workspace tab",
  "Onde a agência encontra cliente novo e vende mais para quem já está com você.":
    "Where your agency finds new clients and sells more to the ones you already have.",
  "A IA procura empresas do seu nicho e região, com motivo e primeira mensagem para cada uma.":
    "The AI finds businesses in your niche and region, each with a reason and a first message.",
  "Buscar prospects": "Find prospects",
  "Nenhum prospect ainda": "No prospects yet",
  "Uma página com pitch, pacotes e prazo. O prospect aceita sem login e já vira cliente.":
    "A page with the pitch, packages and deadline. The prospect accepts without logging in and becomes a client.",
  "Criar proposta": "Create a proposal",
  "Serviços, trabalhos e depoimentos no seu endereço. O formulário vira prospect e avisa você.":
    "Services, work and testimonials at your own address. The form turns into a prospect and alerts you.",
  "Configurar página": "Set up the page",
  "Ainda não publicada": "Not published yet",
  // Admin: custos, teto e LGPD
  "Custos de IA": "AI costs",
  "Margem por conta (30 dias)": "Margin per account (30 days)",
  "Custo por ação e modelo (30 dias)": "Cost per action and model (30 days)",
  "Sem receita nem uso de IA nos últimos 30 dias.": "No revenue or AI usage in the last 30 days.",
  "Nenhum uso de IA registrado.": "No AI usage recorded.",
  "Receita": "Revenue",
  "Custo IA": "AI cost",
  "Margem": "Margin",
  "Chamadas": "Calls",
  "Buscas": "Searches",
  "Ação": "Action",
  "Modelo": "Model",
  "Salvar teto": "Save cap",
  "Teto de IA salvo.": "AI cap saved.",
  "vazio = padrão do plano": "empty = plan default",
  "Dados pessoais (LGPD)": "Personal data (LGPD)",
  "Exportar dados da conta": "Export account data",
  "Excluir conta": "Delete account",
  "Para excluir, digite": "To delete, type",
  "Conta excluída. Lançamentos financeiros ficam sem vínculo pessoal.": "Account deleted. Financial records stay without any personal link.",
  "A exclusão apaga a conta e o que é só dela; pagamentos e custos ficam para a contabilidade, sem vínculo com a pessoa.":
    "Deleting removes the account and what belongs only to it; payments and costs stay for accounting, with no link to the person.",
  "Escreva o motivo da concessão.": "Write the reason for the grant.",
  "Digite o nome de usuário exato para confirmar.": "Type the exact username to confirm.",
  "Use Minha conta para excluir a própria conta.": "Use My account to delete your own account.",
  "Esta conta não usa IA.": "This account doesn't use AI.",
  // Aprovação por link
  "Enviar para aprovação": "Send for approval",
  "Aprovação por link": "Approval by link",
  "Mande posts e entregas pelo WhatsApp. O cliente aprova sem senha e o post já entra na agenda.":
    "Send posts and deliveries over WhatsApp. The client approves without a password and the post goes straight into the schedule.",
  "O cliente aprova pelo celular, sem login. O post aprovado já entra na agenda.":
    "The client approves from their phone, no login. An approved post goes straight into the schedule.",
  "Link pronto. O cliente abre no celular e aprova sem senha.": "Link ready. The client opens it on their phone and approves without a password.",
  "Enviar no WhatsApp": "Send on WhatsApp",
  "Copiar link": "Copy link",
  "Copiar mensagem": "Copy message",
  "Em reunião? O cliente aponta a câmera e abre direto.": "In a meeting? The client points their camera and it opens.",
  "O que vai para aprovação": "What goes for approval",
  "Nada pendente: crie posts no calendário ou suba entregas nas demandas deste cliente.":
    "Nothing pending: create posts in the calendar or upload deliveries in this client's jobs.",
  "Entrega": "Delivery",
  "Validade": "Valid for",
  "WhatsApp do cliente (opcional)": "Client's WhatsApp (optional)",
  "Gerando...": "Generating...",
  "Links enviados": "Links sent",
  "Aberto": "Open",
  "Expirado": "Expired",
  "Encerrado": "Closed",
  "Reenviar": "Resend",
  "Encerrar": "Close",
  "Encerrar este link? O cliente passa a ver que ele expirou.": "Close this link? The client will see that it has expired.",
  "Cadastre um cliente primeiro.": "Add a client first.",
  "Aguardando o cliente": "Waiting for the client",
  "Aprovado pelo cliente": "Approved by the client",
  "Cliente pediu ajuste": "Client asked for changes",
  "Ajuste pedido pelo cliente": "Changes asked by the client",
  "Pelo link de aprovação": "Through the approval link",
  "⏳ Aguardando aprovação há mais de 48h": "⏳ Waiting for approval for over 48h",
  "3 dias": "3 days",
  "7 dias": "7 days",
  "14 dias": "14 days",
  "30 dias": "30 days",
  "Escolha pelo menos um item.": "Pick at least one item.",
  "Escolha pelo menos um post ou entrega.": "Pick at least one post or delivery.",
  "Algum item não é deste cliente ou já foi publicado.": "Some item isn't from this client or was already published.",
  // Pacote do cliente + escopo
  "Pacote": "Package",
  "Pacote do cliente": "Client package",
  "Ver pacote": "View package",
  "Definir pacote": "Set up package",
  "Diga o que o fee cobre por mês. Pedido fora do combinado vira extra com valor aprovado pelo cliente.":
    "Say what the monthly fee covers. Anything outside it becomes an extra with a price the client approves.",
  "O que o fee cobre por mês": "What the fee covers each month",
  "O cliente vê quanto já usou. Pedido que passa do pacote só vira demanda depois que ele aprova o valor do extra — e o extra entra na fatura do mês.":
    "The client sees how much is used. A request beyond the package only becomes a job after they approve the extra's price — and the extra goes on that month's invoice.",
  "Comece por um modelo e ajuste:": "Start from a template and adjust:",
  "Social básico": "Social basics",
  "Social + tráfego": "Social + ads",
  "Conteúdo premium": "Premium content",
  "Item": "Item",
  "Unidade": "Unit",
  "Por mês": "Per month",
  "Extra (R$/un.)": "Extra (R$/unit)",
  "Remover item": "Remove item",
  "+ Adicionar item": "+ Add item",
  "Novo item": "New item",
  "Acumular o que sobrar para o mês seguinte (um mês)": "Carry what's left over to the next month (one month)",
  "Salvar pacote": "Save package",
  "Sem pacote": "No package",
  "Tirar o pacote deste cliente? Os pedidos voltam a virar demanda direto.": "Remove this client's package? Requests will become jobs directly again.",
  "Defina o pacote para acompanhar o uso.": "Set up the package to track usage.",
  "Pedidos do cliente": "Client requests",
  "Os pedidos feitos no portal aparecem aqui, com o que cabe no pacote e o que é extra.":
    "Requests made in the portal show up here, with what fits the package and what's extra.",
  "Aguardando o cliente aprovar o valor": "Waiting for the client to approve the price",
  "Extra aprovado": "Extra approved",
  "Dentro do pacote": "Within the package",
  "Incluído sem custo": "Included at no cost",
  "Incluir sem custo": "Include at no cost",
  "Cancelar pedido": "Cancel request",
  "posts": "posts",
  "reels": "reels",
  "carrosséis": "carousels",
  "stories": "stories",
  "demandas": "jobs",
  "reuniões": "meetings",
  "relatórios": "reports",
  "Posts no feed": "Feed posts",
  "Peças para anúncio": "Ad creatives",
  "Relatório mensal": "Monthly report",
  "Produções extras (foto, vídeo, arte)": "Extra productions (photo, video, design)",
  "Solicitar uma produção": "Request a production",
  "Precisa de algo? Descreva e a solicitação vira uma demanda no painel da agência na hora.":
    "Need something? Describe it and the request becomes a job on the agency's board right away.",
  "✅ Pedido enviado! Cabe no seu pacote e a agência já recebeu.": "✅ Request sent! It fits your package and the agency already has it.",
  "Esse pedido passa do seu pacote. Aprove o valor abaixo para a agência começar.": "This request goes beyond your package. Approve the price below so the agency can start.",
  "Continuar": "Continue",
  "📋 Enviar solicitação": "📋 Send request",
  "Enviando...": "Sending...",
  "O que é": "What it is",
  "Quantidade": "Quantity",
  "Enviar e ver o valor": "Send and see the price",
  "Enviar pedido": "Send request",
  "Voltar": "Back",
  "💰 Extras do mês": "💰 This month's extras",
  "Os extras aprovados entram na fatura do mês de cada cliente.": "Approved extras go on each client's invoice for the month.",
  "Quem aprova o valor do extra é o cliente.": "Only the client approves the extra's price.",
  "Este pedido já foi decidido.": "This request has already been decided.",
  "Conte o que você precisa.": "Tell us what you need.",
  "Escolha um item do pacote.": "Pick an item from the package.",
  "Confira os itens do pacote.": "Check the package items.",
  "Classificação de exemplo (modo de teste).": "Example classification (test mode).",
  // Cobranças (Pix)
  "Cobranças": "Billing",
  "Fatura do fee com Pix copia e cola e QR. O dinheiro vai direto para a sua conta, sem taxa da Marqa.":
    "Fee invoices with a Pix copy-and-paste code and QR. The money goes straight to your account, with no Marqa fee.",
  "Cadastre sua chave Pix em": "Add your Pix key in",
  "Configurações → Recebimentos": "Settings → Payments",
  "para enviar faturas.": "to send invoices.",
  "A receber": "To receive",
  "Atrasadas": "Overdue",
  "Cliente avisou que pagou": "Client says they paid",
  "Nova fatura": "New invoice",
  "No dia 1 a Marqa cria o rascunho de cada cliente com fee (mais os extras aprovados). Você confere e envia. O Pix cai direto na sua conta; a confirmação é sua.":
    "On day 1 Marqa drafts an invoice for each client with a fee (plus approved extras). You check it and send it. The Pix lands in your account; you confirm it.",
  "Escolha o cliente": "Choose the client",
  "Mês": "Month",
  "Criar rascunho": "Create draft",
  "Baixar CSV": "Download CSV",
  "Nenhuma fatura ainda. Defina o fee mensal do cliente em Horas & margem e crie o primeiro rascunho.":
    "No invoices yet. Set the client's monthly fee in Hours & margin and create the first draft.",
  "Rascunho": "Draft",
  "Enviada": "Sent",
  "Cliente diz que pagou": "Client says they paid",
  "Paga": "Paid",
  "Cancelada": "Canceled",
  "Atrasada": "Overdue",
  "Enviar": "Send",
  "Editar": "Edit",
  "Confirmar pagamento": "Confirm payment",
  "Lembrar no WhatsApp": "Remind on WhatsApp",
  "Desfazer confirmação": "Undo confirmation",
  "Ver página do cliente ↗": "View client page ↗",
  "Cancelar fatura": "Cancel invoice",
  "Cancelar esta fatura? Os extras voltam para a próxima.": "Cancel this invoice? The extras move to the next one.",
  "O pagamento cai direto na sua conta; a confirmação é manual. A Marqa não cobra taxa sobre as faturas.":
    "The payment lands straight in your account; confirmation is manual. Marqa charges no fee on invoices.",
  "Cadastre sua chave Pix em Configurações": "Add your Pix key in Settings",
  "Descrição": "Description",
  "Valor": "Amount",
  "Vencimento": "Due date",
  "+ Linha": "+ Line",
  "Salvar": "Save",
  "Recebimentos (Pix)": "Payments (Pix)",
  "As faturas dos clientes saem com Pix copia e cola e QR da sua chave. O pagamento cai direto na sua conta — a Marqa não passa o dinheiro nem cobra taxa. A confirmação do pagamento é sua.":
    "Client invoices go out with a Pix copy-and-paste code and QR for your key. The payment lands straight in your account — Marqa never handles the money or charges a fee. You confirm each payment.",
  "Chave Pix": "Pix key",
  "CNPJ, CPF, e-mail, celular ou chave aleatória": "CNPJ, CPF, email, mobile or random key",
  "Nome de quem recebe": "Recipient name",
  "Como aparece no banco": "As it appears at the bank",
  "Cidade": "City",
  "Dia do vencimento": "Due day",
  "Aviso de atraso (opcional)": "Late notice (optional)",
  "Ex.: após o vencimento, multa de 2% conforme contrato": "E.g.: after the due date, 2% fine as per contract",
  "Salvar recebimentos": "Save payment details",
  "Pronto para enviar faturas": "Ready to send invoices",
  "Faltam dados para enviar faturas": "Details missing to send invoices",
  "Financeiro": "Billing",
  "Em aberto": "Open",
  "Aguardando confirmação": "Awaiting confirmation",
  "🧾 Faturas": "🧾 Invoices",
  "Cobranças →": "Billing →",
  "Lembrar": "Remind",
  "Recebido": "Received",
  "Cadastre sua chave Pix em Configurações → Recebimentos.": "Add your Pix key in Settings → Payments.",
  "Envie a fatura primeiro.": "Send the invoice first.",
  "Só dá para editar a fatura antes de enviar.": "An invoice can only be edited before it's sent.",
  "A fatura precisa de pelo menos uma linha.": "The invoice needs at least one line.",
  "Sem fee nem extras neste mês. Defina o fee do cliente em Horas & margem ou adicione uma linha.":
    "No fee or extras this month. Set the client's fee in Hours & margin or add a line.",
  "Chave Pix inválida. Use CPF, CNPJ, e-mail, celular ou chave aleatória.": "Invalid Pix key. Use CPF, CNPJ, email, mobile or a random key.",
  "Confira os dados de recebimento.": "Check the payment details.",
  "Escolha o cliente e o mês.": "Choose the client and the month.",
  // Assinatura no cartão
  "Assinatura enviada ao Mercado Pago. O plano liga assim que a primeira cobrança no cartão for aprovada.":
    "Subscription sent to Mercado Pago. The plan turns on as soon as the first card charge is approved.",
  "Preços em reais (R$), cobrados pelo Mercado Pago.": "Prices in Brazilian reais (R$), billed in BRL by Mercado Pago.",
  "Assinatura no cartão: renova sozinha no período escolhido; cancele quando quiser e o plano vale até o fim do período pago. Ou pague um período à vista (Pix, boleto ou cartão), sem renovação.":
    "Card subscription: renews on its own for the period you pick; cancel anytime and the plan lasts until the end of the paid period. Or pay one period up front (Pix, boleto or card), with no renewal.",
  "Os planos são pagos por período (Pix, cartão ou boleto) e não renovam sozinhos: no fim do período a conta volta para o grátis.":
    "Plans are paid per period (Pix, card or boleto) and don't renew on their own: at the end of the period the account goes back to free.",
  "Arrependimento em até 7 dias —": "7-day cooling-off period —",
  "Assinatura no cartão (Mercado Pago)": "Card subscription (Mercado Pago)",
  "Cancelar renovação": "Cancel renewal",
  "Cancelar a renovação no cartão? Seu plano continua até o fim do período já pago.": "Cancel the card renewal? Your plan continues until the end of the period already paid.",
  "Qual e-mail você usa no Mercado Pago? A assinatura fica ligada a ele.": "Which email do you use on Mercado Pago? The subscription is linked to it.",
  "E-mail do Mercado Pago": "Mercado Pago email",
  "Assinar no cartão · mensal": "Subscribe by card · monthly",
  "Pagar o período à vista (Pix/boleto)": "Pay the period up front (Pix/boleto)",
  "Informe o e-mail da conta do Mercado Pago.": "Enter the email of your Mercado Pago account.",
  "Não foi possível abrir a assinatura agora. Tente de novo em instantes.": "We couldn't open the subscription right now. Try again shortly.",
  "Não há assinatura no cartão para cancelar.": "There's no card subscription to cancel.",
  "Não conseguimos cancelar no Mercado Pago agora. Tente de novo em instantes.": "We couldn't cancel on Mercado Pago right now. Try again shortly.",
};

export const UI_REGEX_R3: [RegExp, string][] = [
  [/^Cancelada — o plano vale até (.+) e depois volta para o grátis\.$/, "Canceled — the plan lasts until $1 and then goes back to free."],
  [/^Próxima cobrança em (.+)\. Sem fidelidade: cancele quando quiser\.$/, "Next charge on $1. No lock-in: cancel anytime."],
  [/^Renovação cancelada\. Seu plano vale até (.+)\.$/, "Renewal canceled. Your plan lasts until $1."],
  [/^Assinar no cartão · a cada (\d+) meses$/, "Subscribe by card · every $1 months"],
  [/^Vence (\d{2}\/\d{2}) · (\d+) linha\(s\)$/, "Due $1 · $2 line(s)"],
  [/^· atrasada há (\d+) dia\(s\)$/, "· $1 day(s) overdue"],
  [/^(\d+) fatura\(s\) vencem esta semana · (.+)$/, "$1 invoice(s) due this week · $2"],
  [/^(\d+) cliente\(s\) avisaram que pagaram — confira e confirme$/, "$1 client(s) say they paid — check and confirm"],
  [/^(\d+) rascunho\(s\) esperando envio$/, "$1 draft(s) waiting to be sent"],
  [/^Uso em (.+)$/, "Usage in $1"],
  [/^Pacote de (.+)$/, "$1 package"],
  [/^Seu pacote em (.+):$/, "Your package in $1:"],
  [/^Aprovar extra de (.+)$/, "Approve extra of $1"],
  [/^(\d+) extra\(s\) esperando o cliente aprovar o valor$/, "$1 extra(s) waiting for the client to approve the price"],
  [/^(\d+) pedido\(s\) esperando o cliente aprovar o valor$/, "$1 request(s) waiting for the client to approve the price"],
  [/^Extras aprovados este mês: (.+)$/, "Extras approved this month: $1"],
  [/^Cabe no seu pacote \(sobram (\d+)\)\.$/, "Fits your package ($1 left)."],
  [/^Isso passa do seu pacote: \+(.+)\. A agência só começa depois que você aprovar\.$/, "This goes beyond your package: +$1. The agency only starts once you approve."],
  [/^Gerar link \((\d+)\)$/, "Create link ($1)"],
  [/^(\d+) itens · (\d+) sem resposta · aberto (\d+)x$/, "$1 items · $2 unanswered · opened $3x"],
  [/^· (\d+) sem resposta$/, "· $1 unanswered"],
  [/^Ajuste pedido por (.+)$/, "Changes asked by $1"],
  [/^Teto diário de IA \(US\$\) · hoje (.+) de sem teto próprio$/, "Daily AI cap (US$) · today $1, no cap of its own"],
  [/^Teto diário de IA \(US\$\) · hoje (.+) de (.+)$/, "Daily AI cap (US$) · today $1 of $2"],

  [/^(\d+) prospects salvos$/, "$1 saved prospects"],
  [/^(\d+) em aberto · (\d+) aceitas$/, "$1 open · $2 accepted"],
  [/^Publicada · (\d+) pedidos recebidos$/, "Published · $1 requests received"],
];
